// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniproxy/ui/ent/org"
)

// Org is the model entity for the Org schema.
type Org struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Organization display name
	Name string `json:"name,omitempty"`
	// URL-friendly unique identifier
	Slug string `json:"slug,omitempty"`
	// Subscription plan
	Plan org.Plan `json:"plan,omitempty"`
	// How long to retain traffic data
	TrafficRetentionDays int `json:"traffic_retention_days,omitempty"`
	// Maximum number of proxy instances
	MaxProxies int `json:"max_proxies,omitempty"`
	// Whether the org is active
	Active bool `json:"active,omitempty"`
	// When the org was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the org was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrgQuery when eager-loading is set.
	Edges        OrgEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrgEdges holds the relations/edges for other nodes in the graph.
type OrgEdges struct {
	// Users belonging to this org
	Users []*User `json:"users,omitempty"`
	// Proxy instances belonging to this org
	Proxies []*Proxy `json:"proxies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e OrgEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// ProxiesOrErr returns the Proxies value or an error if the edge
// was not loaded in eager-loading.
func (e OrgEdges) ProxiesOrErr() ([]*Proxy, error) {
	if e.loadedTypes[1] {
		return e.Proxies, nil
	}
	return nil, &NotLoadedError{edge: "proxies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Org) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case org.FieldActive:
			values[i] = new(sql.NullBool)
		case org.FieldID, org.FieldTrafficRetentionDays, org.FieldMaxProxies:
			values[i] = new(sql.NullInt64)
		case org.FieldName, org.FieldSlug, org.FieldPlan:
			values[i] = new(sql.NullString)
		case org.FieldCreatedAt, org.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Org fields.
func (_m *Org) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case org.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case org.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case org.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case org.FieldPlan:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan", values[i])
			} else if value.Valid {
				_m.Plan = org.Plan(value.String)
			}
		case org.FieldTrafficRetentionDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field traffic_retention_days", values[i])
			} else if value.Valid {
				_m.TrafficRetentionDays = int(value.Int64)
			}
		case org.FieldMaxProxies:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_proxies", values[i])
			} else if value.Valid {
				_m.MaxProxies = int(value.Int64)
			}
		case org.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case org.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case org.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Org.
// This includes values selected through modifiers, order, etc.
func (_m *Org) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Org entity.
func (_m *Org) QueryUsers() *UserQuery {
	return NewOrgClient(_m.config).QueryUsers(_m)
}

// QueryProxies queries the "proxies" edge of the Org entity.
func (_m *Org) QueryProxies() *ProxyQuery {
	return NewOrgClient(_m.config).QueryProxies(_m)
}

// Update returns a builder for updating this Org.
// Note that you need to call Org.Unwrap() before calling this method if this Org
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Org) Update() *OrgUpdateOne {
	return NewOrgClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Org entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Org) Unwrap() *Org {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Org is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Org) String() string {
	var builder strings.Builder
	builder.WriteString("Org(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("plan=")
	builder.WriteString(fmt.Sprintf("%v", _m.Plan))
	builder.WriteString(", ")
	builder.WriteString("traffic_retention_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrafficRetentionDays))
	builder.WriteString(", ")
	builder.WriteString("max_proxies=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxProxies))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Orgs is a parsable slice of Org.
type Orgs []*Org
