// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniproxy/ui/ent/org"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/user"
)

// OrgCreate is the builder for creating a Org entity.
type OrgCreate struct {
	config
	mutation *OrgMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *OrgCreate) SetName(v string) *OrgCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *OrgCreate) SetSlug(v string) *OrgCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetPlan sets the "plan" field.
func (_c *OrgCreate) SetPlan(v org.Plan) *OrgCreate {
	_c.mutation.SetPlan(v)
	return _c
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_c *OrgCreate) SetNillablePlan(v *org.Plan) *OrgCreate {
	if v != nil {
		_c.SetPlan(*v)
	}
	return _c
}

// SetTrafficRetentionDays sets the "traffic_retention_days" field.
func (_c *OrgCreate) SetTrafficRetentionDays(v int) *OrgCreate {
	_c.mutation.SetTrafficRetentionDays(v)
	return _c
}

// SetNillableTrafficRetentionDays sets the "traffic_retention_days" field if the given value is not nil.
func (_c *OrgCreate) SetNillableTrafficRetentionDays(v *int) *OrgCreate {
	if v != nil {
		_c.SetTrafficRetentionDays(*v)
	}
	return _c
}

// SetMaxProxies sets the "max_proxies" field.
func (_c *OrgCreate) SetMaxProxies(v int) *OrgCreate {
	_c.mutation.SetMaxProxies(v)
	return _c
}

// SetNillableMaxProxies sets the "max_proxies" field if the given value is not nil.
func (_c *OrgCreate) SetNillableMaxProxies(v *int) *OrgCreate {
	if v != nil {
		_c.SetMaxProxies(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *OrgCreate) SetActive(v bool) *OrgCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *OrgCreate) SetNillableActive(v *bool) *OrgCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgCreate) SetCreatedAt(v time.Time) *OrgCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgCreate) SetNillableCreatedAt(v *time.Time) *OrgCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgCreate) SetUpdatedAt(v time.Time) *OrgCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgCreate) SetNillableUpdatedAt(v *time.Time) *OrgCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *OrgCreate) AddUserIDs(ids ...int) *OrgCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *OrgCreate) AddUsers(v ...*User) *OrgCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// AddProxyIDs adds the "proxies" edge to the Proxy entity by IDs.
func (_c *OrgCreate) AddProxyIDs(ids ...int) *OrgCreate {
	_c.mutation.AddProxyIDs(ids...)
	return _c
}

// AddProxies adds the "proxies" edges to the Proxy entity.
func (_c *OrgCreate) AddProxies(v ...*Proxy) *OrgCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProxyIDs(ids...)
}

// Mutation returns the OrgMutation object of the builder.
func (_c *OrgCreate) Mutation() *OrgMutation {
	return _c.mutation
}

// Save creates the Org in the database.
func (_c *OrgCreate) Save(ctx context.Context) (*Org, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgCreate) SaveX(ctx context.Context) *Org {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgCreate) defaults() {
	if _, ok := _c.mutation.Plan(); !ok {
		v := org.DefaultPlan
		_c.mutation.SetPlan(v)
	}
	if _, ok := _c.mutation.TrafficRetentionDays(); !ok {
		v := org.DefaultTrafficRetentionDays
		_c.mutation.SetTrafficRetentionDays(v)
	}
	if _, ok := _c.mutation.MaxProxies(); !ok {
		v := org.DefaultMaxProxies
		_c.mutation.SetMaxProxies(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := org.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := org.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := org.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Org.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := org.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Org.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Org.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := org.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Org.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Plan(); !ok {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required field "Org.plan"`)}
	}
	if v, ok := _c.mutation.Plan(); ok {
		if err := org.PlanValidator(v); err != nil {
			return &ValidationError{Name: "plan", err: fmt.Errorf(`ent: validator failed for field "Org.plan": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrafficRetentionDays(); !ok {
		return &ValidationError{Name: "traffic_retention_days", err: errors.New(`ent: missing required field "Org.traffic_retention_days"`)}
	}
	if _, ok := _c.mutation.MaxProxies(); !ok {
		return &ValidationError{Name: "max_proxies", err: errors.New(`ent: missing required field "Org.max_proxies"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Org.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Org.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Org.updated_at"`)}
	}
	return nil
}

func (_c *OrgCreate) sqlSave(ctx context.Context) (*Org, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgCreate) createSpec() (*Org, *sqlgraph.CreateSpec) {
	var (
		_node = &Org{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(org.Table, sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(org.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(org.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Plan(); ok {
		_spec.SetField(org.FieldPlan, field.TypeEnum, value)
		_node.Plan = value
	}
	if value, ok := _c.mutation.TrafficRetentionDays(); ok {
		_spec.SetField(org.FieldTrafficRetentionDays, field.TypeInt, value)
		_node.TrafficRetentionDays = value
	}
	if value, ok := _c.mutation.MaxProxies(); ok {
		_spec.SetField(org.FieldMaxProxies, field.TypeInt, value)
		_node.MaxProxies = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(org.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(org.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(org.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.UsersTable,
			Columns: []string{org.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProxiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.ProxiesTable,
			Columns: []string{org.ProxiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrgCreateBulk is the builder for creating many Org entities in bulk.
type OrgCreateBulk struct {
	config
	err      error
	builders []*OrgCreate
}

// Save creates the Org entities in the database.
func (_c *OrgCreateBulk) Save(ctx context.Context) ([]*Org, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Org, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgCreateBulk) SaveX(ctx context.Context) []*Org {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
