// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniproxy/ui/ent/org"
	"github.com/grokify/omniproxy/ui/ent/proxy"
)

// Proxy is the model entity for the Proxy schema.
type Proxy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Display name for this proxy
	Name string `json:"name,omitempty"`
	// URL-friendly identifier within org
	Slug string `json:"slug,omitempty"`
	// Proxy operating mode
	Mode proxy.Mode `json:"mode,omitempty"`
	// Port to listen on
	Port int `json:"port,omitempty"`
	// Host to bind to
	Host string `json:"host,omitempty"`
	// Enable HTTPS MITM interception
	MitmEnabled bool `json:"mitm_enabled,omitempty"`
	// Hosts to skip MITM for
	SkipHosts []string `json:"skip_hosts,omitempty"`
	// Only capture traffic for these hosts
	IncludeHosts []string `json:"include_hosts,omitempty"`
	// Exclude traffic from these hosts
	ExcludeHosts []string `json:"exclude_hosts,omitempty"`
	// Only capture traffic for these paths
	IncludePaths []string `json:"include_paths,omitempty"`
	// Exclude traffic matching these paths
	ExcludePaths []string `json:"exclude_paths,omitempty"`
	// Upstream proxy URL
	Upstream string `json:"upstream,omitempty"`
	// Skip capturing binary content
	SkipBinary bool `json:"skip_binary,omitempty"`
	// Whether the proxy is active
	Active bool `json:"active,omitempty"`
	// Last time the proxy was started
	LastStartedAt *time.Time `json:"last_started_at,omitempty"`
	// When the proxy was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the proxy was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyQuery when eager-loading is set.
	Edges        ProxyEdges `json:"edges"`
	org_proxies  *int
	selectValues sql.SelectValues
}

// ProxyEdges holds the relations/edges for other nodes in the graph.
type ProxyEdges struct {
	// Organization this proxy belongs to
	Org *Org `json:"org,omitempty"`
	// Traffic captured by this proxy
	Traffic []*Traffic `json:"traffic,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrgOrErr returns the Org value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProxyEdges) OrgOrErr() (*Org, error) {
	if e.Org != nil {
		return e.Org, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: org.Label}
	}
	return nil, &NotLoadedError{edge: "org"}
}

// TrafficOrErr returns the Traffic value or an error if the edge
// was not loaded in eager-loading.
func (e ProxyEdges) TrafficOrErr() ([]*Traffic, error) {
	if e.loadedTypes[1] {
		return e.Traffic, nil
	}
	return nil, &NotLoadedError{edge: "traffic"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Proxy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxy.FieldSkipHosts, proxy.FieldIncludeHosts, proxy.FieldExcludeHosts, proxy.FieldIncludePaths, proxy.FieldExcludePaths:
			values[i] = new([]byte)
		case proxy.FieldMitmEnabled, proxy.FieldSkipBinary, proxy.FieldActive:
			values[i] = new(sql.NullBool)
		case proxy.FieldID, proxy.FieldPort:
			values[i] = new(sql.NullInt64)
		case proxy.FieldName, proxy.FieldSlug, proxy.FieldMode, proxy.FieldHost, proxy.FieldUpstream:
			values[i] = new(sql.NullString)
		case proxy.FieldLastStartedAt, proxy.FieldCreatedAt, proxy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case proxy.ForeignKeys[0]: // org_proxies
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Proxy fields.
func (_m *Proxy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case proxy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxy.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case proxy.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = proxy.Mode(value.String)
			}
		case proxy.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case proxy.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case proxy.FieldMitmEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mitm_enabled", values[i])
			} else if value.Valid {
				_m.MitmEnabled = value.Bool
			}
		case proxy.FieldSkipHosts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field skip_hosts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SkipHosts); err != nil {
					return fmt.Errorf("unmarshal field skip_hosts: %w", err)
				}
			}
		case proxy.FieldIncludeHosts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field include_hosts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IncludeHosts); err != nil {
					return fmt.Errorf("unmarshal field include_hosts: %w", err)
				}
			}
		case proxy.FieldExcludeHosts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field exclude_hosts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExcludeHosts); err != nil {
					return fmt.Errorf("unmarshal field exclude_hosts: %w", err)
				}
			}
		case proxy.FieldIncludePaths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field include_paths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IncludePaths); err != nil {
					return fmt.Errorf("unmarshal field include_paths: %w", err)
				}
			}
		case proxy.FieldExcludePaths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field exclude_paths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExcludePaths); err != nil {
					return fmt.Errorf("unmarshal field exclude_paths: %w", err)
				}
			}
		case proxy.FieldUpstream:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream", values[i])
			} else if value.Valid {
				_m.Upstream = value.String
			}
		case proxy.FieldSkipBinary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field skip_binary", values[i])
			} else if value.Valid {
				_m.SkipBinary = value.Bool
			}
		case proxy.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case proxy.FieldLastStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_started_at", values[i])
			} else if value.Valid {
				_m.LastStartedAt = new(time.Time)
				*_m.LastStartedAt = value.Time
			}
		case proxy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxy.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field org_proxies", value)
			} else if value.Valid {
				_m.org_proxies = new(int)
				*_m.org_proxies = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Proxy.
// This includes values selected through modifiers, order, etc.
func (_m *Proxy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrg queries the "org" edge of the Proxy entity.
func (_m *Proxy) QueryOrg() *OrgQuery {
	return NewProxyClient(_m.config).QueryOrg(_m)
}

// QueryTraffic queries the "traffic" edge of the Proxy entity.
func (_m *Proxy) QueryTraffic() *TrafficQuery {
	return NewProxyClient(_m.config).QueryTraffic(_m)
}

// Update returns a builder for updating this Proxy.
// Note that you need to call Proxy.Unwrap() before calling this method if this Proxy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Proxy) Update() *ProxyUpdateOne {
	return NewProxyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Proxy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Proxy) Unwrap() *Proxy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Proxy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Proxy) String() string {
	var builder strings.Builder
	builder.WriteString("Proxy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("mitm_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.MitmEnabled))
	builder.WriteString(", ")
	builder.WriteString("skip_hosts=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipHosts))
	builder.WriteString(", ")
	builder.WriteString("include_hosts=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncludeHosts))
	builder.WriteString(", ")
	builder.WriteString("exclude_hosts=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExcludeHosts))
	builder.WriteString(", ")
	builder.WriteString("include_paths=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncludePaths))
	builder.WriteString(", ")
	builder.WriteString("exclude_paths=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExcludePaths))
	builder.WriteString(", ")
	builder.WriteString("upstream=")
	builder.WriteString(_m.Upstream)
	builder.WriteString(", ")
	builder.WriteString("skip_binary=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipBinary))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	if v := _m.LastStartedAt; v != nil {
		builder.WriteString("last_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Proxies is a parsable slice of Proxy.
type Proxies []*Proxy
