// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniproxy/ui/ent/org"
	"github.com/grokify/omniproxy/ui/ent/predicate"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/traffic"
)

// ProxyUpdate is the builder for updating Proxy entities.
type ProxyUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyMutation
}

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdate) Where(ps ...predicate.Proxy) *ProxyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyUpdate) SetName(v string) *ProxyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableName(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ProxyUpdate) SetSlug(v string) *ProxyUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableSlug(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *ProxyUpdate) SetMode(v proxy.Mode) *ProxyUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableMode(v *proxy.Mode) *ProxyUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxyUpdate) SetPort(v int) *ProxyUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePort(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxyUpdate) AddPort(v int) *ProxyUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetHost sets the "host" field.
func (_u *ProxyUpdate) SetHost(v string) *ProxyUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableHost(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetMitmEnabled sets the "mitm_enabled" field.
func (_u *ProxyUpdate) SetMitmEnabled(v bool) *ProxyUpdate {
	_u.mutation.SetMitmEnabled(v)
	return _u
}

// SetNillableMitmEnabled sets the "mitm_enabled" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableMitmEnabled(v *bool) *ProxyUpdate {
	if v != nil {
		_u.SetMitmEnabled(*v)
	}
	return _u
}

// SetSkipHosts sets the "skip_hosts" field.
func (_u *ProxyUpdate) SetSkipHosts(v []string) *ProxyUpdate {
	_u.mutation.SetSkipHosts(v)
	return _u
}

// AppendSkipHosts appends value to the "skip_hosts" field.
func (_u *ProxyUpdate) AppendSkipHosts(v []string) *ProxyUpdate {
	_u.mutation.AppendSkipHosts(v)
	return _u
}

// ClearSkipHosts clears the value of the "skip_hosts" field.
func (_u *ProxyUpdate) ClearSkipHosts() *ProxyUpdate {
	_u.mutation.ClearSkipHosts()
	return _u
}

// SetIncludeHosts sets the "include_hosts" field.
func (_u *ProxyUpdate) SetIncludeHosts(v []string) *ProxyUpdate {
	_u.mutation.SetIncludeHosts(v)
	return _u
}

// AppendIncludeHosts appends value to the "include_hosts" field.
func (_u *ProxyUpdate) AppendIncludeHosts(v []string) *ProxyUpdate {
	_u.mutation.AppendIncludeHosts(v)
	return _u
}

// ClearIncludeHosts clears the value of the "include_hosts" field.
func (_u *ProxyUpdate) ClearIncludeHosts() *ProxyUpdate {
	_u.mutation.ClearIncludeHosts()
	return _u
}

// SetExcludeHosts sets the "exclude_hosts" field.
func (_u *ProxyUpdate) SetExcludeHosts(v []string) *ProxyUpdate {
	_u.mutation.SetExcludeHosts(v)
	return _u
}

// AppendExcludeHosts appends value to the "exclude_hosts" field.
func (_u *ProxyUpdate) AppendExcludeHosts(v []string) *ProxyUpdate {
	_u.mutation.AppendExcludeHosts(v)
	return _u
}

// ClearExcludeHosts clears the value of the "exclude_hosts" field.
func (_u *ProxyUpdate) ClearExcludeHosts() *ProxyUpdate {
	_u.mutation.ClearExcludeHosts()
	return _u
}

// SetIncludePaths sets the "include_paths" field.
func (_u *ProxyUpdate) SetIncludePaths(v []string) *ProxyUpdate {
	_u.mutation.SetIncludePaths(v)
	return _u
}

// AppendIncludePaths appends value to the "include_paths" field.
func (_u *ProxyUpdate) AppendIncludePaths(v []string) *ProxyUpdate {
	_u.mutation.AppendIncludePaths(v)
	return _u
}

// ClearIncludePaths clears the value of the "include_paths" field.
func (_u *ProxyUpdate) ClearIncludePaths() *ProxyUpdate {
	_u.mutation.ClearIncludePaths()
	return _u
}

// SetExcludePaths sets the "exclude_paths" field.
func (_u *ProxyUpdate) SetExcludePaths(v []string) *ProxyUpdate {
	_u.mutation.SetExcludePaths(v)
	return _u
}

// AppendExcludePaths appends value to the "exclude_paths" field.
func (_u *ProxyUpdate) AppendExcludePaths(v []string) *ProxyUpdate {
	_u.mutation.AppendExcludePaths(v)
	return _u
}

// ClearExcludePaths clears the value of the "exclude_paths" field.
func (_u *ProxyUpdate) ClearExcludePaths() *ProxyUpdate {
	_u.mutation.ClearExcludePaths()
	return _u
}

// SetUpstream sets the "upstream" field.
func (_u *ProxyUpdate) SetUpstream(v string) *ProxyUpdate {
	_u.mutation.SetUpstream(v)
	return _u
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableUpstream(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetUpstream(*v)
	}
	return _u
}

// ClearUpstream clears the value of the "upstream" field.
func (_u *ProxyUpdate) ClearUpstream() *ProxyUpdate {
	_u.mutation.ClearUpstream()
	return _u
}

// SetSkipBinary sets the "skip_binary" field.
func (_u *ProxyUpdate) SetSkipBinary(v bool) *ProxyUpdate {
	_u.mutation.SetSkipBinary(v)
	return _u
}

// SetNillableSkipBinary sets the "skip_binary" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableSkipBinary(v *bool) *ProxyUpdate {
	if v != nil {
		_u.SetSkipBinary(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *ProxyUpdate) SetActive(v bool) *ProxyUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableActive(v *bool) *ProxyUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetLastStartedAt sets the "last_started_at" field.
func (_u *ProxyUpdate) SetLastStartedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetLastStartedAt(v)
	return _u
}

// SetNillableLastStartedAt sets the "last_started_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableLastStartedAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetLastStartedAt(*v)
	}
	return _u
}

// ClearLastStartedAt clears the value of the "last_started_at" field.
func (_u *ProxyUpdate) ClearLastStartedAt() *ProxyUpdate {
	_u.mutation.ClearLastStartedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdate) SetUpdatedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrgID sets the "org" edge to the Org entity by ID.
func (_u *ProxyUpdate) SetOrgID(id int) *ProxyUpdate {
	_u.mutation.SetOrgID(id)
	return _u
}

// SetOrg sets the "org" edge to the Org entity.
func (_u *ProxyUpdate) SetOrg(v *Org) *ProxyUpdate {
	return _u.SetOrgID(v.ID)
}

// AddTrafficIDs adds the "traffic" edge to the Traffic entity by IDs.
func (_u *ProxyUpdate) AddTrafficIDs(ids ...int) *ProxyUpdate {
	_u.mutation.AddTrafficIDs(ids...)
	return _u
}

// AddTraffic adds the "traffic" edges to the Traffic entity.
func (_u *ProxyUpdate) AddTraffic(v ...*Traffic) *ProxyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrafficIDs(ids...)
}

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdate) Mutation() *ProxyMutation {
	return _u.mutation
}

// ClearOrg clears the "org" edge to the Org entity.
func (_u *ProxyUpdate) ClearOrg() *ProxyUpdate {
	_u.mutation.ClearOrg()
	return _u
}

// ClearTraffic clears all "traffic" edges to the Traffic entity.
func (_u *ProxyUpdate) ClearTraffic() *ProxyUpdate {
	_u.mutation.ClearTraffic()
	return _u
}

// RemoveTrafficIDs removes the "traffic" edge to Traffic entities by IDs.
func (_u *ProxyUpdate) RemoveTrafficIDs(ids ...int) *ProxyUpdate {
	_u.mutation.RemoveTrafficIDs(ids...)
	return _u
}

// RemoveTraffic removes "traffic" edges to Traffic entities.
func (_u *ProxyUpdate) RemoveTraffic(v ...*Traffic) *ProxyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrafficIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := proxy.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Proxy.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := proxy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.mode": %w`, err)}
		}
	}
	if _u.mutation.OrgCleared() && len(_u.mutation.OrgIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Proxy.org"`)
	}
	return nil
}

func (_u *ProxyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(proxy.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(proxy.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.MitmEnabled(); ok {
		_spec.SetField(proxy.FieldMitmEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SkipHosts(); ok {
		_spec.SetField(proxy.FieldSkipHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkipHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldSkipHosts, value)
		})
	}
	if _u.mutation.SkipHostsCleared() {
		_spec.ClearField(proxy.FieldSkipHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.IncludeHosts(); ok {
		_spec.SetField(proxy.FieldIncludeHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIncludeHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldIncludeHosts, value)
		})
	}
	if _u.mutation.IncludeHostsCleared() {
		_spec.ClearField(proxy.FieldIncludeHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExcludeHosts(); ok {
		_spec.SetField(proxy.FieldExcludeHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExcludeHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldExcludeHosts, value)
		})
	}
	if _u.mutation.ExcludeHostsCleared() {
		_spec.ClearField(proxy.FieldExcludeHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.IncludePaths(); ok {
		_spec.SetField(proxy.FieldIncludePaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIncludePaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldIncludePaths, value)
		})
	}
	if _u.mutation.IncludePathsCleared() {
		_spec.ClearField(proxy.FieldIncludePaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExcludePaths(); ok {
		_spec.SetField(proxy.FieldExcludePaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExcludePaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldExcludePaths, value)
		})
	}
	if _u.mutation.ExcludePathsCleared() {
		_spec.ClearField(proxy.FieldExcludePaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.Upstream(); ok {
		_spec.SetField(proxy.FieldUpstream, field.TypeString, value)
	}
	if _u.mutation.UpstreamCleared() {
		_spec.ClearField(proxy.FieldUpstream, field.TypeString)
	}
	if value, ok := _u.mutation.SkipBinary(); ok {
		_spec.SetField(proxy.FieldSkipBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(proxy.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastStartedAt(); ok {
		_spec.SetField(proxy.FieldLastStartedAt, field.TypeTime, value)
	}
	if _u.mutation.LastStartedAtCleared() {
		_spec.ClearField(proxy.FieldLastStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrgCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxy.OrgTable,
			Columns: []string{proxy.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxy.OrgTable,
			Columns: []string{proxy.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrafficCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTrafficIDs(); len(nodes) > 0 && !_u.mutation.TrafficCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrafficIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyUpdateOne is the builder for updating a single Proxy entity.
type ProxyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyMutation
}

// SetName sets the "name" field.
func (_u *ProxyUpdateOne) SetName(v string) *ProxyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableName(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ProxyUpdateOne) SetSlug(v string) *ProxyUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableSlug(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *ProxyUpdateOne) SetMode(v proxy.Mode) *ProxyUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableMode(v *proxy.Mode) *ProxyUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxyUpdateOne) SetPort(v int) *ProxyUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePort(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxyUpdateOne) AddPort(v int) *ProxyUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetHost sets the "host" field.
func (_u *ProxyUpdateOne) SetHost(v string) *ProxyUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableHost(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetMitmEnabled sets the "mitm_enabled" field.
func (_u *ProxyUpdateOne) SetMitmEnabled(v bool) *ProxyUpdateOne {
	_u.mutation.SetMitmEnabled(v)
	return _u
}

// SetNillableMitmEnabled sets the "mitm_enabled" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableMitmEnabled(v *bool) *ProxyUpdateOne {
	if v != nil {
		_u.SetMitmEnabled(*v)
	}
	return _u
}

// SetSkipHosts sets the "skip_hosts" field.
func (_u *ProxyUpdateOne) SetSkipHosts(v []string) *ProxyUpdateOne {
	_u.mutation.SetSkipHosts(v)
	return _u
}

// AppendSkipHosts appends value to the "skip_hosts" field.
func (_u *ProxyUpdateOne) AppendSkipHosts(v []string) *ProxyUpdateOne {
	_u.mutation.AppendSkipHosts(v)
	return _u
}

// ClearSkipHosts clears the value of the "skip_hosts" field.
func (_u *ProxyUpdateOne) ClearSkipHosts() *ProxyUpdateOne {
	_u.mutation.ClearSkipHosts()
	return _u
}

// SetIncludeHosts sets the "include_hosts" field.
func (_u *ProxyUpdateOne) SetIncludeHosts(v []string) *ProxyUpdateOne {
	_u.mutation.SetIncludeHosts(v)
	return _u
}

// AppendIncludeHosts appends value to the "include_hosts" field.
func (_u *ProxyUpdateOne) AppendIncludeHosts(v []string) *ProxyUpdateOne {
	_u.mutation.AppendIncludeHosts(v)
	return _u
}

// ClearIncludeHosts clears the value of the "include_hosts" field.
func (_u *ProxyUpdateOne) ClearIncludeHosts() *ProxyUpdateOne {
	_u.mutation.ClearIncludeHosts()
	return _u
}

// SetExcludeHosts sets the "exclude_hosts" field.
func (_u *ProxyUpdateOne) SetExcludeHosts(v []string) *ProxyUpdateOne {
	_u.mutation.SetExcludeHosts(v)
	return _u
}

// AppendExcludeHosts appends value to the "exclude_hosts" field.
func (_u *ProxyUpdateOne) AppendExcludeHosts(v []string) *ProxyUpdateOne {
	_u.mutation.AppendExcludeHosts(v)
	return _u
}

// ClearExcludeHosts clears the value of the "exclude_hosts" field.
func (_u *ProxyUpdateOne) ClearExcludeHosts() *ProxyUpdateOne {
	_u.mutation.ClearExcludeHosts()
	return _u
}

// SetIncludePaths sets the "include_paths" field.
func (_u *ProxyUpdateOne) SetIncludePaths(v []string) *ProxyUpdateOne {
	_u.mutation.SetIncludePaths(v)
	return _u
}

// AppendIncludePaths appends value to the "include_paths" field.
func (_u *ProxyUpdateOne) AppendIncludePaths(v []string) *ProxyUpdateOne {
	_u.mutation.AppendIncludePaths(v)
	return _u
}

// ClearIncludePaths clears the value of the "include_paths" field.
func (_u *ProxyUpdateOne) ClearIncludePaths() *ProxyUpdateOne {
	_u.mutation.ClearIncludePaths()
	return _u
}

// SetExcludePaths sets the "exclude_paths" field.
func (_u *ProxyUpdateOne) SetExcludePaths(v []string) *ProxyUpdateOne {
	_u.mutation.SetExcludePaths(v)
	return _u
}

// AppendExcludePaths appends value to the "exclude_paths" field.
func (_u *ProxyUpdateOne) AppendExcludePaths(v []string) *ProxyUpdateOne {
	_u.mutation.AppendExcludePaths(v)
	return _u
}

// ClearExcludePaths clears the value of the "exclude_paths" field.
func (_u *ProxyUpdateOne) ClearExcludePaths() *ProxyUpdateOne {
	_u.mutation.ClearExcludePaths()
	return _u
}

// SetUpstream sets the "upstream" field.
func (_u *ProxyUpdateOne) SetUpstream(v string) *ProxyUpdateOne {
	_u.mutation.SetUpstream(v)
	return _u
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableUpstream(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetUpstream(*v)
	}
	return _u
}

// ClearUpstream clears the value of the "upstream" field.
func (_u *ProxyUpdateOne) ClearUpstream() *ProxyUpdateOne {
	_u.mutation.ClearUpstream()
	return _u
}

// SetSkipBinary sets the "skip_binary" field.
func (_u *ProxyUpdateOne) SetSkipBinary(v bool) *ProxyUpdateOne {
	_u.mutation.SetSkipBinary(v)
	return _u
}

// SetNillableSkipBinary sets the "skip_binary" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableSkipBinary(v *bool) *ProxyUpdateOne {
	if v != nil {
		_u.SetSkipBinary(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *ProxyUpdateOne) SetActive(v bool) *ProxyUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableActive(v *bool) *ProxyUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetLastStartedAt sets the "last_started_at" field.
func (_u *ProxyUpdateOne) SetLastStartedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetLastStartedAt(v)
	return _u
}

// SetNillableLastStartedAt sets the "last_started_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableLastStartedAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetLastStartedAt(*v)
	}
	return _u
}

// ClearLastStartedAt clears the value of the "last_started_at" field.
func (_u *ProxyUpdateOne) ClearLastStartedAt() *ProxyUpdateOne {
	_u.mutation.ClearLastStartedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdateOne) SetUpdatedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrgID sets the "org" edge to the Org entity by ID.
func (_u *ProxyUpdateOne) SetOrgID(id int) *ProxyUpdateOne {
	_u.mutation.SetOrgID(id)
	return _u
}

// SetOrg sets the "org" edge to the Org entity.
func (_u *ProxyUpdateOne) SetOrg(v *Org) *ProxyUpdateOne {
	return _u.SetOrgID(v.ID)
}

// AddTrafficIDs adds the "traffic" edge to the Traffic entity by IDs.
func (_u *ProxyUpdateOne) AddTrafficIDs(ids ...int) *ProxyUpdateOne {
	_u.mutation.AddTrafficIDs(ids...)
	return _u
}

// AddTraffic adds the "traffic" edges to the Traffic entity.
func (_u *ProxyUpdateOne) AddTraffic(v ...*Traffic) *ProxyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrafficIDs(ids...)
}

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdateOne) Mutation() *ProxyMutation {
	return _u.mutation
}

// ClearOrg clears the "org" edge to the Org entity.
func (_u *ProxyUpdateOne) ClearOrg() *ProxyUpdateOne {
	_u.mutation.ClearOrg()
	return _u
}

// ClearTraffic clears all "traffic" edges to the Traffic entity.
func (_u *ProxyUpdateOne) ClearTraffic() *ProxyUpdateOne {
	_u.mutation.ClearTraffic()
	return _u
}

// RemoveTrafficIDs removes the "traffic" edge to Traffic entities by IDs.
func (_u *ProxyUpdateOne) RemoveTrafficIDs(ids ...int) *ProxyUpdateOne {
	_u.mutation.RemoveTrafficIDs(ids...)
	return _u
}

// RemoveTraffic removes "traffic" edges to Traffic entities.
func (_u *ProxyUpdateOne) RemoveTraffic(v ...*Traffic) *ProxyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrafficIDs(ids...)
}

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdateOne) Where(ps ...predicate.Proxy) *ProxyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyUpdateOne) Select(field string, fields ...string) *ProxyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Proxy entity.
func (_u *ProxyUpdateOne) Save(ctx context.Context) (*Proxy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdateOne) SaveX(ctx context.Context) *Proxy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := proxy.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Proxy.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := proxy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.mode": %w`, err)}
		}
	}
	if _u.mutation.OrgCleared() && len(_u.mutation.OrgIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Proxy.org"`)
	}
	return nil
}

func (_u *ProxyUpdateOne) sqlSave(ctx context.Context) (_node *Proxy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Proxy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxy.FieldID)
		for _, f := range fields {
			if !proxy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(proxy.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(proxy.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.MitmEnabled(); ok {
		_spec.SetField(proxy.FieldMitmEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SkipHosts(); ok {
		_spec.SetField(proxy.FieldSkipHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkipHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldSkipHosts, value)
		})
	}
	if _u.mutation.SkipHostsCleared() {
		_spec.ClearField(proxy.FieldSkipHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.IncludeHosts(); ok {
		_spec.SetField(proxy.FieldIncludeHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIncludeHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldIncludeHosts, value)
		})
	}
	if _u.mutation.IncludeHostsCleared() {
		_spec.ClearField(proxy.FieldIncludeHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExcludeHosts(); ok {
		_spec.SetField(proxy.FieldExcludeHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExcludeHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldExcludeHosts, value)
		})
	}
	if _u.mutation.ExcludeHostsCleared() {
		_spec.ClearField(proxy.FieldExcludeHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.IncludePaths(); ok {
		_spec.SetField(proxy.FieldIncludePaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIncludePaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldIncludePaths, value)
		})
	}
	if _u.mutation.IncludePathsCleared() {
		_spec.ClearField(proxy.FieldIncludePaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExcludePaths(); ok {
		_spec.SetField(proxy.FieldExcludePaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExcludePaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, proxy.FieldExcludePaths, value)
		})
	}
	if _u.mutation.ExcludePathsCleared() {
		_spec.ClearField(proxy.FieldExcludePaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.Upstream(); ok {
		_spec.SetField(proxy.FieldUpstream, field.TypeString, value)
	}
	if _u.mutation.UpstreamCleared() {
		_spec.ClearField(proxy.FieldUpstream, field.TypeString)
	}
	if value, ok := _u.mutation.SkipBinary(); ok {
		_spec.SetField(proxy.FieldSkipBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(proxy.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastStartedAt(); ok {
		_spec.SetField(proxy.FieldLastStartedAt, field.TypeTime, value)
	}
	if _u.mutation.LastStartedAtCleared() {
		_spec.ClearField(proxy.FieldLastStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrgCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxy.OrgTable,
			Columns: []string{proxy.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxy.OrgTable,
			Columns: []string{proxy.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrafficCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTrafficIDs(); len(nodes) > 0 && !_u.mutation.TrafficCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrafficIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Proxy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
