// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniproxy/ui/ent/org"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/traffic"
)

// ProxyCreate is the builder for creating a Proxy entity.
type ProxyCreate struct {
	config
	mutation *ProxyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProxyCreate) SetName(v string) *ProxyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ProxyCreate) SetSlug(v string) *ProxyCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *ProxyCreate) SetMode(v proxy.Mode) *ProxyCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableMode(v *proxy.Mode) *ProxyCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetPort sets the "port" field.
func (_c *ProxyCreate) SetPort(v int) *ProxyCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_c *ProxyCreate) SetNillablePort(v *int) *ProxyCreate {
	if v != nil {
		_c.SetPort(*v)
	}
	return _c
}

// SetHost sets the "host" field.
func (_c *ProxyCreate) SetHost(v string) *ProxyCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableHost(v *string) *ProxyCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetMitmEnabled sets the "mitm_enabled" field.
func (_c *ProxyCreate) SetMitmEnabled(v bool) *ProxyCreate {
	_c.mutation.SetMitmEnabled(v)
	return _c
}

// SetNillableMitmEnabled sets the "mitm_enabled" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableMitmEnabled(v *bool) *ProxyCreate {
	if v != nil {
		_c.SetMitmEnabled(*v)
	}
	return _c
}

// SetSkipHosts sets the "skip_hosts" field.
func (_c *ProxyCreate) SetSkipHosts(v []string) *ProxyCreate {
	_c.mutation.SetSkipHosts(v)
	return _c
}

// SetIncludeHosts sets the "include_hosts" field.
func (_c *ProxyCreate) SetIncludeHosts(v []string) *ProxyCreate {
	_c.mutation.SetIncludeHosts(v)
	return _c
}

// SetExcludeHosts sets the "exclude_hosts" field.
func (_c *ProxyCreate) SetExcludeHosts(v []string) *ProxyCreate {
	_c.mutation.SetExcludeHosts(v)
	return _c
}

// SetIncludePaths sets the "include_paths" field.
func (_c *ProxyCreate) SetIncludePaths(v []string) *ProxyCreate {
	_c.mutation.SetIncludePaths(v)
	return _c
}

// SetExcludePaths sets the "exclude_paths" field.
func (_c *ProxyCreate) SetExcludePaths(v []string) *ProxyCreate {
	_c.mutation.SetExcludePaths(v)
	return _c
}

// SetUpstream sets the "upstream" field.
func (_c *ProxyCreate) SetUpstream(v string) *ProxyCreate {
	_c.mutation.SetUpstream(v)
	return _c
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableUpstream(v *string) *ProxyCreate {
	if v != nil {
		_c.SetUpstream(*v)
	}
	return _c
}

// SetSkipBinary sets the "skip_binary" field.
func (_c *ProxyCreate) SetSkipBinary(v bool) *ProxyCreate {
	_c.mutation.SetSkipBinary(v)
	return _c
}

// SetNillableSkipBinary sets the "skip_binary" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableSkipBinary(v *bool) *ProxyCreate {
	if v != nil {
		_c.SetSkipBinary(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *ProxyCreate) SetActive(v bool) *ProxyCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableActive(v *bool) *ProxyCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetLastStartedAt sets the "last_started_at" field.
func (_c *ProxyCreate) SetLastStartedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetLastStartedAt(v)
	return _c
}

// SetNillableLastStartedAt sets the "last_started_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableLastStartedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetLastStartedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyCreate) SetCreatedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableCreatedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyCreate) SetUpdatedAt(v time.Time) *ProxyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyCreate) SetNillableUpdatedAt(v *time.Time) *ProxyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrgID sets the "org" edge to the Org entity by ID.
func (_c *ProxyCreate) SetOrgID(id int) *ProxyCreate {
	_c.mutation.SetOrgID(id)
	return _c
}

// SetOrg sets the "org" edge to the Org entity.
func (_c *ProxyCreate) SetOrg(v *Org) *ProxyCreate {
	return _c.SetOrgID(v.ID)
}

// AddTrafficIDs adds the "traffic" edge to the Traffic entity by IDs.
func (_c *ProxyCreate) AddTrafficIDs(ids ...int) *ProxyCreate {
	_c.mutation.AddTrafficIDs(ids...)
	return _c
}

// AddTraffic adds the "traffic" edges to the Traffic entity.
func (_c *ProxyCreate) AddTraffic(v ...*Traffic) *ProxyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTrafficIDs(ids...)
}

// Mutation returns the ProxyMutation object of the builder.
func (_c *ProxyCreate) Mutation() *ProxyMutation {
	return _c.mutation
}

// Save creates the Proxy in the database.
func (_c *ProxyCreate) Save(ctx context.Context) (*Proxy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyCreate) SaveX(ctx context.Context) *Proxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyCreate) defaults() {
	if _, ok := _c.mutation.Mode(); !ok {
		v := proxy.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Port(); !ok {
		v := proxy.DefaultPort
		_c.mutation.SetPort(v)
	}
	if _, ok := _c.mutation.Host(); !ok {
		v := proxy.DefaultHost
		_c.mutation.SetHost(v)
	}
	if _, ok := _c.mutation.MitmEnabled(); !ok {
		v := proxy.DefaultMitmEnabled
		_c.mutation.SetMitmEnabled(v)
	}
	if _, ok := _c.mutation.SkipBinary(); !ok {
		v := proxy.DefaultSkipBinary
		_c.mutation.SetSkipBinary(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := proxy.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Proxy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Proxy.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := proxy.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Proxy.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Proxy.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := proxy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "Proxy.port"`)}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Proxy.host"`)}
	}
	if _, ok := _c.mutation.MitmEnabled(); !ok {
		return &ValidationError{Name: "mitm_enabled", err: errors.New(`ent: missing required field "Proxy.mitm_enabled"`)}
	}
	if _, ok := _c.mutation.SkipBinary(); !ok {
		return &ValidationError{Name: "skip_binary", err: errors.New(`ent: missing required field "Proxy.skip_binary"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Proxy.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Proxy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Proxy.updated_at"`)}
	}
	if len(_c.mutation.OrgIDs()) == 0 {
		return &ValidationError{Name: "org", err: errors.New(`ent: missing required edge "Proxy.org"`)}
	}
	return nil
}

func (_c *ProxyCreate) sqlSave(ctx context.Context) (*Proxy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyCreate) createSpec() (*Proxy, *sqlgraph.CreateSpec) {
	var (
		_node = &Proxy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxy.Table, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(proxy.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(proxy.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.MitmEnabled(); ok {
		_spec.SetField(proxy.FieldMitmEnabled, field.TypeBool, value)
		_node.MitmEnabled = value
	}
	if value, ok := _c.mutation.SkipHosts(); ok {
		_spec.SetField(proxy.FieldSkipHosts, field.TypeJSON, value)
		_node.SkipHosts = value
	}
	if value, ok := _c.mutation.IncludeHosts(); ok {
		_spec.SetField(proxy.FieldIncludeHosts, field.TypeJSON, value)
		_node.IncludeHosts = value
	}
	if value, ok := _c.mutation.ExcludeHosts(); ok {
		_spec.SetField(proxy.FieldExcludeHosts, field.TypeJSON, value)
		_node.ExcludeHosts = value
	}
	if value, ok := _c.mutation.IncludePaths(); ok {
		_spec.SetField(proxy.FieldIncludePaths, field.TypeJSON, value)
		_node.IncludePaths = value
	}
	if value, ok := _c.mutation.ExcludePaths(); ok {
		_spec.SetField(proxy.FieldExcludePaths, field.TypeJSON, value)
		_node.ExcludePaths = value
	}
	if value, ok := _c.mutation.Upstream(); ok {
		_spec.SetField(proxy.FieldUpstream, field.TypeString, value)
		_node.Upstream = value
	}
	if value, ok := _c.mutation.SkipBinary(); ok {
		_spec.SetField(proxy.FieldSkipBinary, field.TypeBool, value)
		_node.SkipBinary = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(proxy.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.LastStartedAt(); ok {
		_spec.SetField(proxy.FieldLastStartedAt, field.TypeTime, value)
		_node.LastStartedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proxy.OrgTable,
			Columns: []string{proxy.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.org_proxies = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TrafficIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxy.TrafficTable,
			Columns: []string{proxy.TrafficColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProxyCreateBulk is the builder for creating many Proxy entities in bulk.
type ProxyCreateBulk struct {
	config
	err      error
	builders []*ProxyCreate
}

// Save creates the Proxy entities in the database.
func (_c *ProxyCreateBulk) Save(ctx context.Context) ([]*Proxy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Proxy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyCreateBulk) SaveX(ctx context.Context) []*Proxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
