// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/grokify/omniproxy/ui/ent/org"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/schema"
	"github.com/grokify/omniproxy/ui/ent/session"
	"github.com/grokify/omniproxy/ui/ent/traffic"
	"github.com/grokify/omniproxy/ui/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orgFields := schema.Org{}.Fields()
	_ = orgFields
	// orgDescName is the schema descriptor for name field.
	orgDescName := orgFields[0].Descriptor()
	// org.NameValidator is a validator for the "name" field. It is called by the builders before save.
	org.NameValidator = orgDescName.Validators[0].(func(string) error)
	// orgDescSlug is the schema descriptor for slug field.
	orgDescSlug := orgFields[1].Descriptor()
	// org.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	org.SlugValidator = orgDescSlug.Validators[0].(func(string) error)
	// orgDescTrafficRetentionDays is the schema descriptor for traffic_retention_days field.
	orgDescTrafficRetentionDays := orgFields[3].Descriptor()
	// org.DefaultTrafficRetentionDays holds the default value on creation for the traffic_retention_days field.
	org.DefaultTrafficRetentionDays = orgDescTrafficRetentionDays.Default.(int)
	// orgDescMaxProxies is the schema descriptor for max_proxies field.
	orgDescMaxProxies := orgFields[4].Descriptor()
	// org.DefaultMaxProxies holds the default value on creation for the max_proxies field.
	org.DefaultMaxProxies = orgDescMaxProxies.Default.(int)
	// orgDescActive is the schema descriptor for active field.
	orgDescActive := orgFields[5].Descriptor()
	// org.DefaultActive holds the default value on creation for the active field.
	org.DefaultActive = orgDescActive.Default.(bool)
	// orgDescCreatedAt is the schema descriptor for created_at field.
	orgDescCreatedAt := orgFields[6].Descriptor()
	// org.DefaultCreatedAt holds the default value on creation for the created_at field.
	org.DefaultCreatedAt = orgDescCreatedAt.Default.(func() time.Time)
	// orgDescUpdatedAt is the schema descriptor for updated_at field.
	orgDescUpdatedAt := orgFields[7].Descriptor()
	// org.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	org.DefaultUpdatedAt = orgDescUpdatedAt.Default.(func() time.Time)
	// org.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	org.UpdateDefaultUpdatedAt = orgDescUpdatedAt.UpdateDefault.(func() time.Time)
	proxyFields := schema.Proxy{}.Fields()
	_ = proxyFields
	// proxyDescName is the schema descriptor for name field.
	proxyDescName := proxyFields[0].Descriptor()
	// proxy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	proxy.NameValidator = proxyDescName.Validators[0].(func(string) error)
	// proxyDescSlug is the schema descriptor for slug field.
	proxyDescSlug := proxyFields[1].Descriptor()
	// proxy.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	proxy.SlugValidator = proxyDescSlug.Validators[0].(func(string) error)
	// proxyDescPort is the schema descriptor for port field.
	proxyDescPort := proxyFields[3].Descriptor()
	// proxy.DefaultPort holds the default value on creation for the port field.
	proxy.DefaultPort = proxyDescPort.Default.(int)
	// proxyDescHost is the schema descriptor for host field.
	proxyDescHost := proxyFields[4].Descriptor()
	// proxy.DefaultHost holds the default value on creation for the host field.
	proxy.DefaultHost = proxyDescHost.Default.(string)
	// proxyDescMitmEnabled is the schema descriptor for mitm_enabled field.
	proxyDescMitmEnabled := proxyFields[5].Descriptor()
	// proxy.DefaultMitmEnabled holds the default value on creation for the mitm_enabled field.
	proxy.DefaultMitmEnabled = proxyDescMitmEnabled.Default.(bool)
	// proxyDescSkipBinary is the schema descriptor for skip_binary field.
	proxyDescSkipBinary := proxyFields[12].Descriptor()
	// proxy.DefaultSkipBinary holds the default value on creation for the skip_binary field.
	proxy.DefaultSkipBinary = proxyDescSkipBinary.Default.(bool)
	// proxyDescActive is the schema descriptor for active field.
	proxyDescActive := proxyFields[13].Descriptor()
	// proxy.DefaultActive holds the default value on creation for the active field.
	proxy.DefaultActive = proxyDescActive.Default.(bool)
	// proxyDescCreatedAt is the schema descriptor for created_at field.
	proxyDescCreatedAt := proxyFields[15].Descriptor()
	// proxy.DefaultCreatedAt holds the default value on creation for the created_at field.
	proxy.DefaultCreatedAt = proxyDescCreatedAt.Default.(func() time.Time)
	// proxyDescUpdatedAt is the schema descriptor for updated_at field.
	proxyDescUpdatedAt := proxyFields[16].Descriptor()
	// proxy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	proxy.DefaultUpdatedAt = proxyDescUpdatedAt.Default.(func() time.Time)
	// proxy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	proxy.UpdateDefaultUpdatedAt = proxyDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[0].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = sessionDescToken.Validators[0].(func(string) error)
	// sessionDescLastActiveAt is the schema descriptor for last_active_at field.
	sessionDescLastActiveAt := sessionFields[4].Descriptor()
	// session.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	session.DefaultLastActiveAt = sessionDescLastActiveAt.Default.(func() time.Time)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[5].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	trafficFields := schema.Traffic{}.Fields()
	_ = trafficFields
	// trafficDescMethod is the schema descriptor for method field.
	trafficDescMethod := trafficFields[0].Descriptor()
	// traffic.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	traffic.MethodValidator = trafficDescMethod.Validators[0].(func(string) error)
	// trafficDescURL is the schema descriptor for url field.
	trafficDescURL := trafficFields[1].Descriptor()
	// traffic.URLValidator is a validator for the "url" field. It is called by the builders before save.
	traffic.URLValidator = trafficDescURL.Validators[0].(func(string) error)
	// trafficDescHost is the schema descriptor for host field.
	trafficDescHost := trafficFields[3].Descriptor()
	// traffic.HostValidator is a validator for the "host" field. It is called by the builders before save.
	traffic.HostValidator = trafficDescHost.Validators[0].(func(string) error)
	// trafficDescRequestBodySize is the schema descriptor for request_body_size field.
	trafficDescRequestBodySize := trafficFields[8].Descriptor()
	// traffic.DefaultRequestBodySize holds the default value on creation for the request_body_size field.
	traffic.DefaultRequestBodySize = trafficDescRequestBodySize.Default.(int64)
	// trafficDescRequestIsBinary is the schema descriptor for request_is_binary field.
	trafficDescRequestIsBinary := trafficFields[9].Descriptor()
	// traffic.DefaultRequestIsBinary holds the default value on creation for the request_is_binary field.
	traffic.DefaultRequestIsBinary = trafficDescRequestIsBinary.Default.(bool)
	// trafficDescResponseBodySize is the schema descriptor for response_body_size field.
	trafficDescResponseBodySize := trafficFields[15].Descriptor()
	// traffic.DefaultResponseBodySize holds the default value on creation for the response_body_size field.
	traffic.DefaultResponseBodySize = trafficDescResponseBodySize.Default.(int64)
	// trafficDescResponseIsBinary is the schema descriptor for response_is_binary field.
	trafficDescResponseIsBinary := trafficFields[16].Descriptor()
	// traffic.DefaultResponseIsBinary holds the default value on creation for the response_is_binary field.
	traffic.DefaultResponseIsBinary = trafficDescResponseIsBinary.Default.(bool)
	// trafficDescCreatedAt is the schema descriptor for created_at field.
	trafficDescCreatedAt := trafficFields[24].Descriptor()
	// traffic.DefaultCreatedAt holds the default value on creation for the created_at field.
	traffic.DefaultCreatedAt = trafficDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[7].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
