// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniproxy/ui/ent/predicate"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/traffic"
)

// TrafficQuery is the builder for querying Traffic entities.
type TrafficQuery struct {
	config
	ctx        *QueryContext
	order      []traffic.OrderOption
	inters     []Interceptor
	predicates []predicate.Traffic
	withProxy  *ProxyQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrafficQuery builder.
func (_q *TrafficQuery) Where(ps ...predicate.Traffic) *TrafficQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TrafficQuery) Limit(limit int) *TrafficQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TrafficQuery) Offset(offset int) *TrafficQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TrafficQuery) Unique(unique bool) *TrafficQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TrafficQuery) Order(o ...traffic.OrderOption) *TrafficQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProxy chains the current query on the "proxy" edge.
func (_q *TrafficQuery) QueryProxy() *ProxyQuery {
	query := (&ProxyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(traffic.Table, traffic.FieldID, selector),
			sqlgraph.To(proxy.Table, proxy.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, traffic.ProxyTable, traffic.ProxyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Traffic entity from the query.
// Returns a *NotFoundError when no Traffic was found.
func (_q *TrafficQuery) First(ctx context.Context) (*Traffic, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{traffic.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TrafficQuery) FirstX(ctx context.Context) *Traffic {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Traffic ID from the query.
// Returns a *NotFoundError when no Traffic ID was found.
func (_q *TrafficQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{traffic.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TrafficQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Traffic entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Traffic entity is found.
// Returns a *NotFoundError when no Traffic entities are found.
func (_q *TrafficQuery) Only(ctx context.Context) (*Traffic, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{traffic.Label}
	default:
		return nil, &NotSingularError{traffic.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TrafficQuery) OnlyX(ctx context.Context) *Traffic {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Traffic ID in the query.
// Returns a *NotSingularError when more than one Traffic ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TrafficQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{traffic.Label}
	default:
		err = &NotSingularError{traffic.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TrafficQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Traffics.
func (_q *TrafficQuery) All(ctx context.Context) ([]*Traffic, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Traffic, *TrafficQuery]()
	return withInterceptors[[]*Traffic](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TrafficQuery) AllX(ctx context.Context) []*Traffic {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Traffic IDs.
func (_q *TrafficQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(traffic.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TrafficQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TrafficQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TrafficQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TrafficQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TrafficQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TrafficQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrafficQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TrafficQuery) Clone() *TrafficQuery {
	if _q == nil {
		return nil
	}
	return &TrafficQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]traffic.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Traffic{}, _q.predicates...),
		withProxy:  _q.withProxy.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProxy tells the query-builder to eager-load the nodes that are connected to
// the "proxy" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TrafficQuery) WithProxy(opts ...func(*ProxyQuery)) *TrafficQuery {
	query := (&ProxyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProxy = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Method string `json:"method,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Traffic.Query().
//		GroupBy(traffic.FieldMethod).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TrafficQuery) GroupBy(field string, fields ...string) *TrafficGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrafficGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = traffic.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Method string `json:"method,omitempty"`
//	}
//
//	client.Traffic.Query().
//		Select(traffic.FieldMethod).
//		Scan(ctx, &v)
func (_q *TrafficQuery) Select(fields ...string) *TrafficSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TrafficSelect{TrafficQuery: _q}
	sbuild.label = traffic.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrafficSelect configured with the given aggregations.
func (_q *TrafficQuery) Aggregate(fns ...AggregateFunc) *TrafficSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TrafficQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !traffic.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TrafficQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Traffic, error) {
	var (
		nodes       = []*Traffic{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withProxy != nil,
		}
	)
	if _q.withProxy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, traffic.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Traffic).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Traffic{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProxy; query != nil {
		if err := _q.loadProxy(ctx, query, nodes, nil,
			func(n *Traffic, e *Proxy) { n.Edges.Proxy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TrafficQuery) loadProxy(ctx context.Context, query *ProxyQuery, nodes []*Traffic, init func(*Traffic), assign func(*Traffic, *Proxy)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Traffic)
	for i := range nodes {
		if nodes[i].proxy_traffic == nil {
			continue
		}
		fk := *nodes[i].proxy_traffic
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(proxy.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "proxy_traffic" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *TrafficQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TrafficQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(traffic.Table, traffic.Columns, sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, traffic.FieldID)
		for i := range fields {
			if fields[i] != traffic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TrafficQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(traffic.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = traffic.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrafficGroupBy is the group-by builder for Traffic entities.
type TrafficGroupBy struct {
	selector
	build *TrafficQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TrafficGroupBy) Aggregate(fns ...AggregateFunc) *TrafficGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TrafficGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrafficQuery, *TrafficGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TrafficGroupBy) sqlScan(ctx context.Context, root *TrafficQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrafficSelect is the builder for selecting fields of Traffic entities.
type TrafficSelect struct {
	*TrafficQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TrafficSelect) Aggregate(fns ...AggregateFunc) *TrafficSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TrafficSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrafficQuery, *TrafficSelect](ctx, _s.TrafficQuery, _s, _s.inters, v)
}

func (_s *TrafficSelect) sqlScan(ctx context.Context, root *TrafficQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
