// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniproxy/ui/ent/predicate"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/traffic"
)

// TrafficUpdate is the builder for updating Traffic entities.
type TrafficUpdate struct {
	config
	hooks    []Hook
	mutation *TrafficMutation
}

// Where appends a list predicates to the TrafficUpdate builder.
func (_u *TrafficUpdate) Where(ps ...predicate.Traffic) *TrafficUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMethod sets the "method" field.
func (_u *TrafficUpdate) SetMethod(v string) *TrafficUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableMethod(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TrafficUpdate) SetURL(v string) *TrafficUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableURL(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetScheme sets the "scheme" field.
func (_u *TrafficUpdate) SetScheme(v string) *TrafficUpdate {
	_u.mutation.SetScheme(v)
	return _u
}

// SetNillableScheme sets the "scheme" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableScheme(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetScheme(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *TrafficUpdate) SetHost(v string) *TrafficUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableHost(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *TrafficUpdate) SetPath(v string) *TrafficUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillablePath(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *TrafficUpdate) SetQuery(v string) *TrafficUpdate {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableQuery(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// ClearQuery clears the value of the "query" field.
func (_u *TrafficUpdate) ClearQuery() *TrafficUpdate {
	_u.mutation.ClearQuery()
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *TrafficUpdate) SetRequestHeaders(v map[string][]string) *TrafficUpdate {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// ClearRequestHeaders clears the value of the "request_headers" field.
func (_u *TrafficUpdate) ClearRequestHeaders() *TrafficUpdate {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *TrafficUpdate) SetRequestBody(v []byte) *TrafficUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *TrafficUpdate) ClearRequestBody() *TrafficUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestBodySize sets the "request_body_size" field.
func (_u *TrafficUpdate) SetRequestBodySize(v int64) *TrafficUpdate {
	_u.mutation.ResetRequestBodySize()
	_u.mutation.SetRequestBodySize(v)
	return _u
}

// SetNillableRequestBodySize sets the "request_body_size" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableRequestBodySize(v *int64) *TrafficUpdate {
	if v != nil {
		_u.SetRequestBodySize(*v)
	}
	return _u
}

// AddRequestBodySize adds value to the "request_body_size" field.
func (_u *TrafficUpdate) AddRequestBodySize(v int64) *TrafficUpdate {
	_u.mutation.AddRequestBodySize(v)
	return _u
}

// SetRequestIsBinary sets the "request_is_binary" field.
func (_u *TrafficUpdate) SetRequestIsBinary(v bool) *TrafficUpdate {
	_u.mutation.SetRequestIsBinary(v)
	return _u
}

// SetNillableRequestIsBinary sets the "request_is_binary" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableRequestIsBinary(v *bool) *TrafficUpdate {
	if v != nil {
		_u.SetRequestIsBinary(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *TrafficUpdate) SetContentType(v string) *TrafficUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableContentType(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *TrafficUpdate) ClearContentType() *TrafficUpdate {
	_u.mutation.ClearContentType()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *TrafficUpdate) SetStatusCode(v int) *TrafficUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableStatusCode(v *int) *TrafficUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *TrafficUpdate) AddStatusCode(v int) *TrafficUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetStatusText sets the "status_text" field.
func (_u *TrafficUpdate) SetStatusText(v string) *TrafficUpdate {
	_u.mutation.SetStatusText(v)
	return _u
}

// SetNillableStatusText sets the "status_text" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableStatusText(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetStatusText(*v)
	}
	return _u
}

// ClearStatusText clears the value of the "status_text" field.
func (_u *TrafficUpdate) ClearStatusText() *TrafficUpdate {
	_u.mutation.ClearStatusText()
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *TrafficUpdate) SetResponseHeaders(v map[string][]string) *TrafficUpdate {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (_u *TrafficUpdate) ClearResponseHeaders() *TrafficUpdate {
	_u.mutation.ClearResponseHeaders()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *TrafficUpdate) SetResponseBody(v []byte) *TrafficUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *TrafficUpdate) ClearResponseBody() *TrafficUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseBodySize sets the "response_body_size" field.
func (_u *TrafficUpdate) SetResponseBodySize(v int64) *TrafficUpdate {
	_u.mutation.ResetResponseBodySize()
	_u.mutation.SetResponseBodySize(v)
	return _u
}

// SetNillableResponseBodySize sets the "response_body_size" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableResponseBodySize(v *int64) *TrafficUpdate {
	if v != nil {
		_u.SetResponseBodySize(*v)
	}
	return _u
}

// AddResponseBodySize adds value to the "response_body_size" field.
func (_u *TrafficUpdate) AddResponseBodySize(v int64) *TrafficUpdate {
	_u.mutation.AddResponseBodySize(v)
	return _u
}

// SetResponseIsBinary sets the "response_is_binary" field.
func (_u *TrafficUpdate) SetResponseIsBinary(v bool) *TrafficUpdate {
	_u.mutation.SetResponseIsBinary(v)
	return _u
}

// SetNillableResponseIsBinary sets the "response_is_binary" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableResponseIsBinary(v *bool) *TrafficUpdate {
	if v != nil {
		_u.SetResponseIsBinary(*v)
	}
	return _u
}

// SetResponseContentType sets the "response_content_type" field.
func (_u *TrafficUpdate) SetResponseContentType(v string) *TrafficUpdate {
	_u.mutation.SetResponseContentType(v)
	return _u
}

// SetNillableResponseContentType sets the "response_content_type" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableResponseContentType(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetResponseContentType(*v)
	}
	return _u
}

// ClearResponseContentType clears the value of the "response_content_type" field.
func (_u *TrafficUpdate) ClearResponseContentType() *TrafficUpdate {
	_u.mutation.ClearResponseContentType()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TrafficUpdate) SetStartedAt(v time.Time) *TrafficUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableStartedAt(v *time.Time) *TrafficUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *TrafficUpdate) SetDurationMs(v float64) *TrafficUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableDurationMs(v *float64) *TrafficUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *TrafficUpdate) AddDurationMs(v float64) *TrafficUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_u *TrafficUpdate) SetTtfbMs(v float64) *TrafficUpdate {
	_u.mutation.ResetTtfbMs()
	_u.mutation.SetTtfbMs(v)
	return _u
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableTtfbMs(v *float64) *TrafficUpdate {
	if v != nil {
		_u.SetTtfbMs(*v)
	}
	return _u
}

// AddTtfbMs adds value to the "ttfb_ms" field.
func (_u *TrafficUpdate) AddTtfbMs(v float64) *TrafficUpdate {
	_u.mutation.AddTtfbMs(v)
	return _u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (_u *TrafficUpdate) ClearTtfbMs() *TrafficUpdate {
	_u.mutation.ClearTtfbMs()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *TrafficUpdate) SetClientIP(v string) *TrafficUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableClientIP(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *TrafficUpdate) ClearClientIP() *TrafficUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetError sets the "error" field.
func (_u *TrafficUpdate) SetError(v string) *TrafficUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *TrafficUpdate) SetNillableError(v *string) *TrafficUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *TrafficUpdate) ClearError() *TrafficUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetTags sets the "tags" field.
func (_u *TrafficUpdate) SetTags(v []string) *TrafficUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *TrafficUpdate) AppendTags(v []string) *TrafficUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *TrafficUpdate) ClearTags() *TrafficUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetProxyID sets the "proxy" edge to the Proxy entity by ID.
func (_u *TrafficUpdate) SetProxyID(id int) *TrafficUpdate {
	_u.mutation.SetProxyID(id)
	return _u
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *TrafficUpdate) SetProxy(v *Proxy) *TrafficUpdate {
	return _u.SetProxyID(v.ID)
}

// Mutation returns the TrafficMutation object of the builder.
func (_u *TrafficUpdate) Mutation() *TrafficMutation {
	return _u.mutation
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *TrafficUpdate) ClearProxy() *TrafficUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrafficUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrafficUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrafficUpdate) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := traffic.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Traffic.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := traffic.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Traffic.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := traffic.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Traffic.host": %w`, err)}
		}
	}
	if _u.mutation.ProxyCleared() && len(_u.mutation.ProxyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Traffic.proxy"`)
	}
	return nil
}

func (_u *TrafficUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(traffic.Table, traffic.Columns, sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(traffic.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(traffic.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scheme(); ok {
		_spec.SetField(traffic.FieldScheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(traffic.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(traffic.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(traffic.FieldQuery, field.TypeString, value)
	}
	if _u.mutation.QueryCleared() {
		_spec.ClearField(traffic.FieldQuery, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(traffic.FieldRequestHeaders, field.TypeJSON, value)
	}
	if _u.mutation.RequestHeadersCleared() {
		_spec.ClearField(traffic.FieldRequestHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(traffic.FieldRequestBody, field.TypeBytes, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(traffic.FieldRequestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.RequestBodySize(); ok {
		_spec.SetField(traffic.FieldRequestBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestBodySize(); ok {
		_spec.AddField(traffic.FieldRequestBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestIsBinary(); ok {
		_spec.SetField(traffic.FieldRequestIsBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(traffic.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(traffic.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(traffic.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(traffic.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StatusText(); ok {
		_spec.SetField(traffic.FieldStatusText, field.TypeString, value)
	}
	if _u.mutation.StatusTextCleared() {
		_spec.ClearField(traffic.FieldStatusText, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(traffic.FieldResponseHeaders, field.TypeJSON, value)
	}
	if _u.mutation.ResponseHeadersCleared() {
		_spec.ClearField(traffic.FieldResponseHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(traffic.FieldResponseBody, field.TypeBytes, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(traffic.FieldResponseBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ResponseBodySize(); ok {
		_spec.SetField(traffic.FieldResponseBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResponseBodySize(); ok {
		_spec.AddField(traffic.FieldResponseBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResponseIsBinary(); ok {
		_spec.SetField(traffic.FieldResponseIsBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseContentType(); ok {
		_spec.SetField(traffic.FieldResponseContentType, field.TypeString, value)
	}
	if _u.mutation.ResponseContentTypeCleared() {
		_spec.ClearField(traffic.FieldResponseContentType, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(traffic.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(traffic.FieldDurationMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(traffic.FieldDurationMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TtfbMs(); ok {
		_spec.SetField(traffic.FieldTtfbMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTtfbMs(); ok {
		_spec.AddField(traffic.FieldTtfbMs, field.TypeFloat64, value)
	}
	if _u.mutation.TtfbMsCleared() {
		_spec.ClearField(traffic.FieldTtfbMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(traffic.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(traffic.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(traffic.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(traffic.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(traffic.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, traffic.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(traffic.FieldTags, field.TypeJSON)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   traffic.ProxyTable,
			Columns: []string{traffic.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   traffic.ProxyTable,
			Columns: []string{traffic.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{traffic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrafficUpdateOne is the builder for updating a single Traffic entity.
type TrafficUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrafficMutation
}

// SetMethod sets the "method" field.
func (_u *TrafficUpdateOne) SetMethod(v string) *TrafficUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableMethod(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TrafficUpdateOne) SetURL(v string) *TrafficUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableURL(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetScheme sets the "scheme" field.
func (_u *TrafficUpdateOne) SetScheme(v string) *TrafficUpdateOne {
	_u.mutation.SetScheme(v)
	return _u
}

// SetNillableScheme sets the "scheme" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableScheme(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetScheme(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *TrafficUpdateOne) SetHost(v string) *TrafficUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableHost(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *TrafficUpdateOne) SetPath(v string) *TrafficUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillablePath(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *TrafficUpdateOne) SetQuery(v string) *TrafficUpdateOne {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableQuery(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// ClearQuery clears the value of the "query" field.
func (_u *TrafficUpdateOne) ClearQuery() *TrafficUpdateOne {
	_u.mutation.ClearQuery()
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *TrafficUpdateOne) SetRequestHeaders(v map[string][]string) *TrafficUpdateOne {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// ClearRequestHeaders clears the value of the "request_headers" field.
func (_u *TrafficUpdateOne) ClearRequestHeaders() *TrafficUpdateOne {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *TrafficUpdateOne) SetRequestBody(v []byte) *TrafficUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *TrafficUpdateOne) ClearRequestBody() *TrafficUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestBodySize sets the "request_body_size" field.
func (_u *TrafficUpdateOne) SetRequestBodySize(v int64) *TrafficUpdateOne {
	_u.mutation.ResetRequestBodySize()
	_u.mutation.SetRequestBodySize(v)
	return _u
}

// SetNillableRequestBodySize sets the "request_body_size" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableRequestBodySize(v *int64) *TrafficUpdateOne {
	if v != nil {
		_u.SetRequestBodySize(*v)
	}
	return _u
}

// AddRequestBodySize adds value to the "request_body_size" field.
func (_u *TrafficUpdateOne) AddRequestBodySize(v int64) *TrafficUpdateOne {
	_u.mutation.AddRequestBodySize(v)
	return _u
}

// SetRequestIsBinary sets the "request_is_binary" field.
func (_u *TrafficUpdateOne) SetRequestIsBinary(v bool) *TrafficUpdateOne {
	_u.mutation.SetRequestIsBinary(v)
	return _u
}

// SetNillableRequestIsBinary sets the "request_is_binary" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableRequestIsBinary(v *bool) *TrafficUpdateOne {
	if v != nil {
		_u.SetRequestIsBinary(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *TrafficUpdateOne) SetContentType(v string) *TrafficUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableContentType(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *TrafficUpdateOne) ClearContentType() *TrafficUpdateOne {
	_u.mutation.ClearContentType()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *TrafficUpdateOne) SetStatusCode(v int) *TrafficUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableStatusCode(v *int) *TrafficUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *TrafficUpdateOne) AddStatusCode(v int) *TrafficUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetStatusText sets the "status_text" field.
func (_u *TrafficUpdateOne) SetStatusText(v string) *TrafficUpdateOne {
	_u.mutation.SetStatusText(v)
	return _u
}

// SetNillableStatusText sets the "status_text" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableStatusText(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetStatusText(*v)
	}
	return _u
}

// ClearStatusText clears the value of the "status_text" field.
func (_u *TrafficUpdateOne) ClearStatusText() *TrafficUpdateOne {
	_u.mutation.ClearStatusText()
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *TrafficUpdateOne) SetResponseHeaders(v map[string][]string) *TrafficUpdateOne {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (_u *TrafficUpdateOne) ClearResponseHeaders() *TrafficUpdateOne {
	_u.mutation.ClearResponseHeaders()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *TrafficUpdateOne) SetResponseBody(v []byte) *TrafficUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *TrafficUpdateOne) ClearResponseBody() *TrafficUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseBodySize sets the "response_body_size" field.
func (_u *TrafficUpdateOne) SetResponseBodySize(v int64) *TrafficUpdateOne {
	_u.mutation.ResetResponseBodySize()
	_u.mutation.SetResponseBodySize(v)
	return _u
}

// SetNillableResponseBodySize sets the "response_body_size" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableResponseBodySize(v *int64) *TrafficUpdateOne {
	if v != nil {
		_u.SetResponseBodySize(*v)
	}
	return _u
}

// AddResponseBodySize adds value to the "response_body_size" field.
func (_u *TrafficUpdateOne) AddResponseBodySize(v int64) *TrafficUpdateOne {
	_u.mutation.AddResponseBodySize(v)
	return _u
}

// SetResponseIsBinary sets the "response_is_binary" field.
func (_u *TrafficUpdateOne) SetResponseIsBinary(v bool) *TrafficUpdateOne {
	_u.mutation.SetResponseIsBinary(v)
	return _u
}

// SetNillableResponseIsBinary sets the "response_is_binary" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableResponseIsBinary(v *bool) *TrafficUpdateOne {
	if v != nil {
		_u.SetResponseIsBinary(*v)
	}
	return _u
}

// SetResponseContentType sets the "response_content_type" field.
func (_u *TrafficUpdateOne) SetResponseContentType(v string) *TrafficUpdateOne {
	_u.mutation.SetResponseContentType(v)
	return _u
}

// SetNillableResponseContentType sets the "response_content_type" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableResponseContentType(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetResponseContentType(*v)
	}
	return _u
}

// ClearResponseContentType clears the value of the "response_content_type" field.
func (_u *TrafficUpdateOne) ClearResponseContentType() *TrafficUpdateOne {
	_u.mutation.ClearResponseContentType()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TrafficUpdateOne) SetStartedAt(v time.Time) *TrafficUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableStartedAt(v *time.Time) *TrafficUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *TrafficUpdateOne) SetDurationMs(v float64) *TrafficUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableDurationMs(v *float64) *TrafficUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *TrafficUpdateOne) AddDurationMs(v float64) *TrafficUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_u *TrafficUpdateOne) SetTtfbMs(v float64) *TrafficUpdateOne {
	_u.mutation.ResetTtfbMs()
	_u.mutation.SetTtfbMs(v)
	return _u
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableTtfbMs(v *float64) *TrafficUpdateOne {
	if v != nil {
		_u.SetTtfbMs(*v)
	}
	return _u
}

// AddTtfbMs adds value to the "ttfb_ms" field.
func (_u *TrafficUpdateOne) AddTtfbMs(v float64) *TrafficUpdateOne {
	_u.mutation.AddTtfbMs(v)
	return _u
}

// ClearTtfbMs clears the value of the "ttfb_ms" field.
func (_u *TrafficUpdateOne) ClearTtfbMs() *TrafficUpdateOne {
	_u.mutation.ClearTtfbMs()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *TrafficUpdateOne) SetClientIP(v string) *TrafficUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableClientIP(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *TrafficUpdateOne) ClearClientIP() *TrafficUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetError sets the "error" field.
func (_u *TrafficUpdateOne) SetError(v string) *TrafficUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *TrafficUpdateOne) SetNillableError(v *string) *TrafficUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *TrafficUpdateOne) ClearError() *TrafficUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetTags sets the "tags" field.
func (_u *TrafficUpdateOne) SetTags(v []string) *TrafficUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *TrafficUpdateOne) AppendTags(v []string) *TrafficUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *TrafficUpdateOne) ClearTags() *TrafficUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetProxyID sets the "proxy" edge to the Proxy entity by ID.
func (_u *TrafficUpdateOne) SetProxyID(id int) *TrafficUpdateOne {
	_u.mutation.SetProxyID(id)
	return _u
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *TrafficUpdateOne) SetProxy(v *Proxy) *TrafficUpdateOne {
	return _u.SetProxyID(v.ID)
}

// Mutation returns the TrafficMutation object of the builder.
func (_u *TrafficUpdateOne) Mutation() *TrafficMutation {
	return _u.mutation
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *TrafficUpdateOne) ClearProxy() *TrafficUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// Where appends a list predicates to the TrafficUpdate builder.
func (_u *TrafficUpdateOne) Where(ps ...predicate.Traffic) *TrafficUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrafficUpdateOne) Select(field string, fields ...string) *TrafficUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Traffic entity.
func (_u *TrafficUpdateOne) Save(ctx context.Context) (*Traffic, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficUpdateOne) SaveX(ctx context.Context) *Traffic {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrafficUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrafficUpdateOne) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := traffic.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Traffic.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := traffic.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Traffic.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := traffic.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Traffic.host": %w`, err)}
		}
	}
	if _u.mutation.ProxyCleared() && len(_u.mutation.ProxyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Traffic.proxy"`)
	}
	return nil
}

func (_u *TrafficUpdateOne) sqlSave(ctx context.Context) (_node *Traffic, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(traffic.Table, traffic.Columns, sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Traffic.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, traffic.FieldID)
		for _, f := range fields {
			if !traffic.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != traffic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(traffic.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(traffic.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scheme(); ok {
		_spec.SetField(traffic.FieldScheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(traffic.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(traffic.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(traffic.FieldQuery, field.TypeString, value)
	}
	if _u.mutation.QueryCleared() {
		_spec.ClearField(traffic.FieldQuery, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(traffic.FieldRequestHeaders, field.TypeJSON, value)
	}
	if _u.mutation.RequestHeadersCleared() {
		_spec.ClearField(traffic.FieldRequestHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(traffic.FieldRequestBody, field.TypeBytes, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(traffic.FieldRequestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.RequestBodySize(); ok {
		_spec.SetField(traffic.FieldRequestBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestBodySize(); ok {
		_spec.AddField(traffic.FieldRequestBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestIsBinary(); ok {
		_spec.SetField(traffic.FieldRequestIsBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(traffic.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(traffic.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(traffic.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(traffic.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StatusText(); ok {
		_spec.SetField(traffic.FieldStatusText, field.TypeString, value)
	}
	if _u.mutation.StatusTextCleared() {
		_spec.ClearField(traffic.FieldStatusText, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(traffic.FieldResponseHeaders, field.TypeJSON, value)
	}
	if _u.mutation.ResponseHeadersCleared() {
		_spec.ClearField(traffic.FieldResponseHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(traffic.FieldResponseBody, field.TypeBytes, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(traffic.FieldResponseBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ResponseBodySize(); ok {
		_spec.SetField(traffic.FieldResponseBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResponseBodySize(); ok {
		_spec.AddField(traffic.FieldResponseBodySize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResponseIsBinary(); ok {
		_spec.SetField(traffic.FieldResponseIsBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseContentType(); ok {
		_spec.SetField(traffic.FieldResponseContentType, field.TypeString, value)
	}
	if _u.mutation.ResponseContentTypeCleared() {
		_spec.ClearField(traffic.FieldResponseContentType, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(traffic.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(traffic.FieldDurationMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(traffic.FieldDurationMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TtfbMs(); ok {
		_spec.SetField(traffic.FieldTtfbMs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTtfbMs(); ok {
		_spec.AddField(traffic.FieldTtfbMs, field.TypeFloat64, value)
	}
	if _u.mutation.TtfbMsCleared() {
		_spec.ClearField(traffic.FieldTtfbMs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(traffic.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(traffic.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(traffic.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(traffic.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(traffic.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, traffic.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(traffic.FieldTags, field.TypeJSON)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   traffic.ProxyTable,
			Columns: []string{traffic.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   traffic.ProxyTable,
			Columns: []string{traffic.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Traffic{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{traffic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
