// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/traffic"
)

// Traffic is the model entity for the Traffic schema.
type Traffic struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// HTTP method (GET, POST, etc.)
	Method string `json:"method,omitempty"`
	// Full request URL
	URL string `json:"url,omitempty"`
	// URL scheme (http/https)
	Scheme string `json:"scheme,omitempty"`
	// Request host
	Host string `json:"host,omitempty"`
	// Request path
	Path string `json:"path,omitempty"`
	// Query string
	Query string `json:"query,omitempty"`
	// Request headers
	RequestHeaders map[string][]string `json:"request_headers,omitempty"`
	// Request body (may be truncated)
	RequestBody []byte `json:"request_body,omitempty"`
	// Original request body size
	RequestBodySize int64 `json:"request_body_size,omitempty"`
	// Whether request body is binary
	RequestIsBinary bool `json:"request_is_binary,omitempty"`
	// Request Content-Type
	ContentType string `json:"content_type,omitempty"`
	// HTTP response status code
	StatusCode int `json:"status_code,omitempty"`
	// HTTP status text
	StatusText string `json:"status_text,omitempty"`
	// Response headers
	ResponseHeaders map[string][]string `json:"response_headers,omitempty"`
	// Response body (may be truncated)
	ResponseBody []byte `json:"response_body,omitempty"`
	// Original response body size
	ResponseBodySize int64 `json:"response_body_size,omitempty"`
	// Whether response body is binary
	ResponseIsBinary bool `json:"response_is_binary,omitempty"`
	// Response Content-Type
	ResponseContentType string `json:"response_content_type,omitempty"`
	// When the request started
	StartedAt time.Time `json:"started_at,omitempty"`
	// Total duration in milliseconds
	DurationMs float64 `json:"duration_ms,omitempty"`
	// Time to first byte in milliseconds
	TtfbMs *float64 `json:"ttfb_ms,omitempty"`
	// Client IP address
	ClientIP string `json:"client_ip,omitempty"`
	// Error message if request failed
	Error string `json:"error,omitempty"`
	// User-defined tags
	Tags []string `json:"tags,omitempty"`
	// When the record was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TrafficQuery when eager-loading is set.
	Edges         TrafficEdges `json:"edges"`
	proxy_traffic *int
	selectValues  sql.SelectValues
}

// TrafficEdges holds the relations/edges for other nodes in the graph.
type TrafficEdges struct {
	// Proxy that captured this traffic
	Proxy *Proxy `json:"proxy,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TrafficEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Traffic) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case traffic.FieldRequestHeaders, traffic.FieldRequestBody, traffic.FieldResponseHeaders, traffic.FieldResponseBody, traffic.FieldTags:
			values[i] = new([]byte)
		case traffic.FieldRequestIsBinary, traffic.FieldResponseIsBinary:
			values[i] = new(sql.NullBool)
		case traffic.FieldDurationMs, traffic.FieldTtfbMs:
			values[i] = new(sql.NullFloat64)
		case traffic.FieldID, traffic.FieldRequestBodySize, traffic.FieldStatusCode, traffic.FieldResponseBodySize:
			values[i] = new(sql.NullInt64)
		case traffic.FieldMethod, traffic.FieldURL, traffic.FieldScheme, traffic.FieldHost, traffic.FieldPath, traffic.FieldQuery, traffic.FieldContentType, traffic.FieldStatusText, traffic.FieldResponseContentType, traffic.FieldClientIP, traffic.FieldError:
			values[i] = new(sql.NullString)
		case traffic.FieldStartedAt, traffic.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case traffic.ForeignKeys[0]: // proxy_traffic
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Traffic fields.
func (_m *Traffic) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case traffic.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case traffic.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case traffic.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case traffic.FieldScheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scheme", values[i])
			} else if value.Valid {
				_m.Scheme = value.String
			}
		case traffic.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case traffic.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case traffic.FieldQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query", values[i])
			} else if value.Valid {
				_m.Query = value.String
			}
		case traffic.FieldRequestHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestHeaders); err != nil {
					return fmt.Errorf("unmarshal field request_headers: %w", err)
				}
			}
		case traffic.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil {
				_m.RequestBody = *value
			}
		case traffic.FieldRequestBodySize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_size", values[i])
			} else if value.Valid {
				_m.RequestBodySize = value.Int64
			}
		case traffic.FieldRequestIsBinary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_is_binary", values[i])
			} else if value.Valid {
				_m.RequestIsBinary = value.Bool
			}
		case traffic.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case traffic.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int(value.Int64)
			}
		case traffic.FieldStatusText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_text", values[i])
			} else if value.Valid {
				_m.StatusText = value.String
			}
		case traffic.FieldResponseHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseHeaders); err != nil {
					return fmt.Errorf("unmarshal field response_headers: %w", err)
				}
			}
		case traffic.FieldResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value != nil {
				_m.ResponseBody = *value
			}
		case traffic.FieldResponseBodySize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_body_size", values[i])
			} else if value.Valid {
				_m.ResponseBodySize = value.Int64
			}
		case traffic.FieldResponseIsBinary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field response_is_binary", values[i])
			} else if value.Valid {
				_m.ResponseIsBinary = value.Bool
			}
		case traffic.FieldResponseContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_content_type", values[i])
			} else if value.Valid {
				_m.ResponseContentType = value.String
			}
		case traffic.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case traffic.FieldDurationMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Float64
			}
		case traffic.FieldTtfbMs:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ttfb_ms", values[i])
			} else if value.Valid {
				_m.TtfbMs = new(float64)
				*_m.TtfbMs = value.Float64
			}
		case traffic.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case traffic.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case traffic.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case traffic.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case traffic.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field proxy_traffic", value)
			} else if value.Valid {
				_m.proxy_traffic = new(int)
				*_m.proxy_traffic = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Traffic.
// This includes values selected through modifiers, order, etc.
func (_m *Traffic) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProxy queries the "proxy" edge of the Traffic entity.
func (_m *Traffic) QueryProxy() *ProxyQuery {
	return NewTrafficClient(_m.config).QueryProxy(_m)
}

// Update returns a builder for updating this Traffic.
// Note that you need to call Traffic.Unwrap() before calling this method if this Traffic
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Traffic) Update() *TrafficUpdateOne {
	return NewTrafficClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Traffic entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Traffic) Unwrap() *Traffic {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Traffic is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Traffic) String() string {
	var builder strings.Builder
	builder.WriteString("Traffic(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("scheme=")
	builder.WriteString(_m.Scheme)
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("query=")
	builder.WriteString(_m.Query)
	builder.WriteString(", ")
	builder.WriteString("request_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestHeaders))
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBody))
	builder.WriteString(", ")
	builder.WriteString("request_body_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestBodySize))
	builder.WriteString(", ")
	builder.WriteString("request_is_binary=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestIsBinary))
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("status_text=")
	builder.WriteString(_m.StatusText)
	builder.WriteString(", ")
	builder.WriteString("response_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseHeaders))
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBody))
	builder.WriteString(", ")
	builder.WriteString("response_body_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseBodySize))
	builder.WriteString(", ")
	builder.WriteString("response_is_binary=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseIsBinary))
	builder.WriteString(", ")
	builder.WriteString("response_content_type=")
	builder.WriteString(_m.ResponseContentType)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	if v := _m.TtfbMs; v != nil {
		builder.WriteString("ttfb_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Traffics is a parsable slice of Traffic.
type Traffics []*Traffic
