// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/omniproxy/ui/ent/proxy"
	"github.com/grokify/omniproxy/ui/ent/traffic"
)

// TrafficCreate is the builder for creating a Traffic entity.
type TrafficCreate struct {
	config
	mutation *TrafficMutation
	hooks    []Hook
}

// SetMethod sets the "method" field.
func (_c *TrafficCreate) SetMethod(v string) *TrafficCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *TrafficCreate) SetURL(v string) *TrafficCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetScheme sets the "scheme" field.
func (_c *TrafficCreate) SetScheme(v string) *TrafficCreate {
	_c.mutation.SetScheme(v)
	return _c
}

// SetHost sets the "host" field.
func (_c *TrafficCreate) SetHost(v string) *TrafficCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *TrafficCreate) SetPath(v string) *TrafficCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *TrafficCreate) SetQuery(v string) *TrafficCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableQuery(v *string) *TrafficCreate {
	if v != nil {
		_c.SetQuery(*v)
	}
	return _c
}

// SetRequestHeaders sets the "request_headers" field.
func (_c *TrafficCreate) SetRequestHeaders(v map[string][]string) *TrafficCreate {
	_c.mutation.SetRequestHeaders(v)
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *TrafficCreate) SetRequestBody(v []byte) *TrafficCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetRequestBodySize sets the "request_body_size" field.
func (_c *TrafficCreate) SetRequestBodySize(v int64) *TrafficCreate {
	_c.mutation.SetRequestBodySize(v)
	return _c
}

// SetNillableRequestBodySize sets the "request_body_size" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableRequestBodySize(v *int64) *TrafficCreate {
	if v != nil {
		_c.SetRequestBodySize(*v)
	}
	return _c
}

// SetRequestIsBinary sets the "request_is_binary" field.
func (_c *TrafficCreate) SetRequestIsBinary(v bool) *TrafficCreate {
	_c.mutation.SetRequestIsBinary(v)
	return _c
}

// SetNillableRequestIsBinary sets the "request_is_binary" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableRequestIsBinary(v *bool) *TrafficCreate {
	if v != nil {
		_c.SetRequestIsBinary(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *TrafficCreate) SetContentType(v string) *TrafficCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableContentType(v *string) *TrafficCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *TrafficCreate) SetStatusCode(v int) *TrafficCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetStatusText sets the "status_text" field.
func (_c *TrafficCreate) SetStatusText(v string) *TrafficCreate {
	_c.mutation.SetStatusText(v)
	return _c
}

// SetNillableStatusText sets the "status_text" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableStatusText(v *string) *TrafficCreate {
	if v != nil {
		_c.SetStatusText(*v)
	}
	return _c
}

// SetResponseHeaders sets the "response_headers" field.
func (_c *TrafficCreate) SetResponseHeaders(v map[string][]string) *TrafficCreate {
	_c.mutation.SetResponseHeaders(v)
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *TrafficCreate) SetResponseBody(v []byte) *TrafficCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetResponseBodySize sets the "response_body_size" field.
func (_c *TrafficCreate) SetResponseBodySize(v int64) *TrafficCreate {
	_c.mutation.SetResponseBodySize(v)
	return _c
}

// SetNillableResponseBodySize sets the "response_body_size" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableResponseBodySize(v *int64) *TrafficCreate {
	if v != nil {
		_c.SetResponseBodySize(*v)
	}
	return _c
}

// SetResponseIsBinary sets the "response_is_binary" field.
func (_c *TrafficCreate) SetResponseIsBinary(v bool) *TrafficCreate {
	_c.mutation.SetResponseIsBinary(v)
	return _c
}

// SetNillableResponseIsBinary sets the "response_is_binary" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableResponseIsBinary(v *bool) *TrafficCreate {
	if v != nil {
		_c.SetResponseIsBinary(*v)
	}
	return _c
}

// SetResponseContentType sets the "response_content_type" field.
func (_c *TrafficCreate) SetResponseContentType(v string) *TrafficCreate {
	_c.mutation.SetResponseContentType(v)
	return _c
}

// SetNillableResponseContentType sets the "response_content_type" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableResponseContentType(v *string) *TrafficCreate {
	if v != nil {
		_c.SetResponseContentType(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *TrafficCreate) SetStartedAt(v time.Time) *TrafficCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *TrafficCreate) SetDurationMs(v float64) *TrafficCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetTtfbMs sets the "ttfb_ms" field.
func (_c *TrafficCreate) SetTtfbMs(v float64) *TrafficCreate {
	_c.mutation.SetTtfbMs(v)
	return _c
}

// SetNillableTtfbMs sets the "ttfb_ms" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableTtfbMs(v *float64) *TrafficCreate {
	if v != nil {
		_c.SetTtfbMs(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *TrafficCreate) SetClientIP(v string) *TrafficCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableClientIP(v *string) *TrafficCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *TrafficCreate) SetError(v string) *TrafficCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableError(v *string) *TrafficCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *TrafficCreate) SetTags(v []string) *TrafficCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TrafficCreate) SetCreatedAt(v time.Time) *TrafficCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TrafficCreate) SetNillableCreatedAt(v *time.Time) *TrafficCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProxyID sets the "proxy" edge to the Proxy entity by ID.
func (_c *TrafficCreate) SetProxyID(id int) *TrafficCreate {
	_c.mutation.SetProxyID(id)
	return _c
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *TrafficCreate) SetProxy(v *Proxy) *TrafficCreate {
	return _c.SetProxyID(v.ID)
}

// Mutation returns the TrafficMutation object of the builder.
func (_c *TrafficCreate) Mutation() *TrafficMutation {
	return _c.mutation
}

// Save creates the Traffic in the database.
func (_c *TrafficCreate) Save(ctx context.Context) (*Traffic, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TrafficCreate) SaveX(ctx context.Context) *Traffic {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrafficCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrafficCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TrafficCreate) defaults() {
	if _, ok := _c.mutation.RequestBodySize(); !ok {
		v := traffic.DefaultRequestBodySize
		_c.mutation.SetRequestBodySize(v)
	}
	if _, ok := _c.mutation.RequestIsBinary(); !ok {
		v := traffic.DefaultRequestIsBinary
		_c.mutation.SetRequestIsBinary(v)
	}
	if _, ok := _c.mutation.ResponseBodySize(); !ok {
		v := traffic.DefaultResponseBodySize
		_c.mutation.SetResponseBodySize(v)
	}
	if _, ok := _c.mutation.ResponseIsBinary(); !ok {
		v := traffic.DefaultResponseIsBinary
		_c.mutation.SetResponseIsBinary(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := traffic.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TrafficCreate) check() error {
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "Traffic.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := traffic.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Traffic.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Traffic.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := traffic.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Traffic.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scheme(); !ok {
		return &ValidationError{Name: "scheme", err: errors.New(`ent: missing required field "Traffic.scheme"`)}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "Traffic.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := traffic.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Traffic.host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Traffic.path"`)}
	}
	if _, ok := _c.mutation.RequestBodySize(); !ok {
		return &ValidationError{Name: "request_body_size", err: errors.New(`ent: missing required field "Traffic.request_body_size"`)}
	}
	if _, ok := _c.mutation.RequestIsBinary(); !ok {
		return &ValidationError{Name: "request_is_binary", err: errors.New(`ent: missing required field "Traffic.request_is_binary"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "Traffic.status_code"`)}
	}
	if _, ok := _c.mutation.ResponseBodySize(); !ok {
		return &ValidationError{Name: "response_body_size", err: errors.New(`ent: missing required field "Traffic.response_body_size"`)}
	}
	if _, ok := _c.mutation.ResponseIsBinary(); !ok {
		return &ValidationError{Name: "response_is_binary", err: errors.New(`ent: missing required field "Traffic.response_is_binary"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Traffic.started_at"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "Traffic.duration_ms"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Traffic.created_at"`)}
	}
	if len(_c.mutation.ProxyIDs()) == 0 {
		return &ValidationError{Name: "proxy", err: errors.New(`ent: missing required edge "Traffic.proxy"`)}
	}
	return nil
}

func (_c *TrafficCreate) sqlSave(ctx context.Context) (*Traffic, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TrafficCreate) createSpec() (*Traffic, *sqlgraph.CreateSpec) {
	var (
		_node = &Traffic{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(traffic.Table, sqlgraph.NewFieldSpec(traffic.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(traffic.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(traffic.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Scheme(); ok {
		_spec.SetField(traffic.FieldScheme, field.TypeString, value)
		_node.Scheme = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(traffic.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(traffic.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(traffic.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.RequestHeaders(); ok {
		_spec.SetField(traffic.FieldRequestHeaders, field.TypeJSON, value)
		_node.RequestHeaders = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(traffic.FieldRequestBody, field.TypeBytes, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.RequestBodySize(); ok {
		_spec.SetField(traffic.FieldRequestBodySize, field.TypeInt64, value)
		_node.RequestBodySize = value
	}
	if value, ok := _c.mutation.RequestIsBinary(); ok {
		_spec.SetField(traffic.FieldRequestIsBinary, field.TypeBool, value)
		_node.RequestIsBinary = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(traffic.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(traffic.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.StatusText(); ok {
		_spec.SetField(traffic.FieldStatusText, field.TypeString, value)
		_node.StatusText = value
	}
	if value, ok := _c.mutation.ResponseHeaders(); ok {
		_spec.SetField(traffic.FieldResponseHeaders, field.TypeJSON, value)
		_node.ResponseHeaders = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(traffic.FieldResponseBody, field.TypeBytes, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ResponseBodySize(); ok {
		_spec.SetField(traffic.FieldResponseBodySize, field.TypeInt64, value)
		_node.ResponseBodySize = value
	}
	if value, ok := _c.mutation.ResponseIsBinary(); ok {
		_spec.SetField(traffic.FieldResponseIsBinary, field.TypeBool, value)
		_node.ResponseIsBinary = value
	}
	if value, ok := _c.mutation.ResponseContentType(); ok {
		_spec.SetField(traffic.FieldResponseContentType, field.TypeString, value)
		_node.ResponseContentType = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(traffic.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(traffic.FieldDurationMs, field.TypeFloat64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.TtfbMs(); ok {
		_spec.SetField(traffic.FieldTtfbMs, field.TypeFloat64, value)
		_node.TtfbMs = &value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(traffic.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(traffic.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(traffic.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(traffic.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   traffic.ProxyTable,
			Columns: []string{traffic.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.proxy_traffic = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TrafficCreateBulk is the builder for creating many Traffic entities in bulk.
type TrafficCreateBulk struct {
	config
	err      error
	builders []*TrafficCreate
}

// Save creates the Traffic entities in the database.
func (_c *TrafficCreateBulk) Save(ctx context.Context) ([]*Traffic, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Traffic, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrafficMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TrafficCreateBulk) SaveX(ctx context.Context) []*Traffic {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrafficCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrafficCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
