// Code generated by ent, DO NOT EDIT.

package org

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the org type in the database.
	Label = "org"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldPlan holds the string denoting the plan field in the database.
	FieldPlan = "plan"
	// FieldTrafficRetentionDays holds the string denoting the traffic_retention_days field in the database.
	FieldTrafficRetentionDays = "traffic_retention_days"
	// FieldMaxProxies holds the string denoting the max_proxies field in the database.
	FieldMaxProxies = "max_proxies"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeProxies holds the string denoting the proxies edge name in mutations.
	EdgeProxies = "proxies"
	// Table holds the table name of the org in the database.
	Table = "orgs"
	// UsersTable is the table that holds the users relation/edge.
	UsersTable = "users"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the users relation/edge.
	UsersColumn = "org_users"
	// ProxiesTable is the table that holds the proxies relation/edge.
	ProxiesTable = "proxies"
	// ProxiesInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxiesInverseTable = "proxies"
	// ProxiesColumn is the table column denoting the proxies relation/edge.
	ProxiesColumn = "org_proxies"
)

// Columns holds all SQL columns for org fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldPlan,
	FieldTrafficRetentionDays,
	FieldMaxProxies,
	FieldActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultTrafficRetentionDays holds the default value on creation for the "traffic_retention_days" field.
	DefaultTrafficRetentionDays int
	// DefaultMaxProxies holds the default value on creation for the "max_proxies" field.
	DefaultMaxProxies int
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Plan defines the type for the "plan" enum field.
type Plan string

// PlanFree is the default value of the Plan enum.
const DefaultPlan = PlanFree

// Plan values.
const (
	PlanFree       Plan = "free"
	PlanTeam       Plan = "team"
	PlanEnterprise Plan = "enterprise"
)

func (pl Plan) String() string {
	return string(pl)
}

// PlanValidator is a validator for the "plan" field enum values. It is called by the builders before save.
func PlanValidator(pl Plan) error {
	switch pl {
	case PlanFree, PlanTeam, PlanEnterprise:
		return nil
	default:
		return fmt.Errorf("org: invalid enum value for plan field: %q", pl)
	}
}

// OrderOption defines the ordering options for the Org queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByPlan orders the results by the plan field.
func ByPlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlan, opts...).ToFunc()
}

// ByTrafficRetentionDays orders the results by the traffic_retention_days field.
func ByTrafficRetentionDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrafficRetentionDays, opts...).ToFunc()
}

// ByMaxProxies orders the results by the max_proxies field.
func ByMaxProxies(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxProxies, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsersCount orders the results by users count.
func ByUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsersStep(), opts...)
	}
}

// ByUsers orders the results by users terms.
func ByUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProxiesCount orders the results by proxies count.
func ByProxiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProxiesStep(), opts...)
	}
}

// ByProxies orders the results by proxies terms.
func ByProxies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
	)
}
func newProxiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProxiesTable, ProxiesColumn),
	)
}
