// Code generated by ent, DO NOT EDIT.

package org

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/grokify/omniproxy/ui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldSlug, v))
}

// TrafficRetentionDays applies equality check predicate on the "traffic_retention_days" field. It's identical to TrafficRetentionDaysEQ.
func TrafficRetentionDays(v int) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldTrafficRetentionDays, v))
}

// MaxProxies applies equality check predicate on the "max_proxies" field. It's identical to MaxProxiesEQ.
func MaxProxies(v int) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldMaxProxies, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Org {
	return predicate.Org(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Org {
	return predicate.Org(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Org {
	return predicate.Org(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Org {
	return predicate.Org(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Org {
	return predicate.Org(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Org {
	return predicate.Org(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Org {
	return predicate.Org(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Org {
	return predicate.Org(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Org {
	return predicate.Org(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Org {
	return predicate.Org(sql.FieldContainsFold(FieldSlug, v))
}

// PlanEQ applies the EQ predicate on the "plan" field.
func PlanEQ(v Plan) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldPlan, v))
}

// PlanNEQ applies the NEQ predicate on the "plan" field.
func PlanNEQ(v Plan) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldPlan, v))
}

// PlanIn applies the In predicate on the "plan" field.
func PlanIn(vs ...Plan) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldPlan, vs...))
}

// PlanNotIn applies the NotIn predicate on the "plan" field.
func PlanNotIn(vs ...Plan) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldPlan, vs...))
}

// TrafficRetentionDaysEQ applies the EQ predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysEQ(v int) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldTrafficRetentionDays, v))
}

// TrafficRetentionDaysNEQ applies the NEQ predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysNEQ(v int) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldTrafficRetentionDays, v))
}

// TrafficRetentionDaysIn applies the In predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysIn(vs ...int) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldTrafficRetentionDays, vs...))
}

// TrafficRetentionDaysNotIn applies the NotIn predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysNotIn(vs ...int) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldTrafficRetentionDays, vs...))
}

// TrafficRetentionDaysGT applies the GT predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysGT(v int) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldTrafficRetentionDays, v))
}

// TrafficRetentionDaysGTE applies the GTE predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysGTE(v int) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldTrafficRetentionDays, v))
}

// TrafficRetentionDaysLT applies the LT predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysLT(v int) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldTrafficRetentionDays, v))
}

// TrafficRetentionDaysLTE applies the LTE predicate on the "traffic_retention_days" field.
func TrafficRetentionDaysLTE(v int) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldTrafficRetentionDays, v))
}

// MaxProxiesEQ applies the EQ predicate on the "max_proxies" field.
func MaxProxiesEQ(v int) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldMaxProxies, v))
}

// MaxProxiesNEQ applies the NEQ predicate on the "max_proxies" field.
func MaxProxiesNEQ(v int) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldMaxProxies, v))
}

// MaxProxiesIn applies the In predicate on the "max_proxies" field.
func MaxProxiesIn(vs ...int) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldMaxProxies, vs...))
}

// MaxProxiesNotIn applies the NotIn predicate on the "max_proxies" field.
func MaxProxiesNotIn(vs ...int) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldMaxProxies, vs...))
}

// MaxProxiesGT applies the GT predicate on the "max_proxies" field.
func MaxProxiesGT(v int) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldMaxProxies, v))
}

// MaxProxiesGTE applies the GTE predicate on the "max_proxies" field.
func MaxProxiesGTE(v int) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldMaxProxies, v))
}

// MaxProxiesLT applies the LT predicate on the "max_proxies" field.
func MaxProxiesLT(v int) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldMaxProxies, v))
}

// MaxProxiesLTE applies the LTE predicate on the "max_proxies" field.
func MaxProxiesLTE(v int) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldMaxProxies, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Org {
	return predicate.Org(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Org {
	return predicate.Org(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Org {
	return predicate.Org(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Org {
	return predicate.Org(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Org {
	return predicate.Org(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProxies applies the HasEdge predicate on the "proxies" edge.
func HasProxies() predicate.Org {
	return predicate.Org(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProxiesTable, ProxiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxiesWith applies the HasEdge predicate on the "proxies" edge with a given conditions (other predicates).
func HasProxiesWith(preds ...predicate.Proxy) predicate.Org {
	return predicate.Org(func(s *sql.Selector) {
		step := newProxiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Org) predicate.Org {
	return predicate.Org(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Org) predicate.Org {
	return predicate.Org(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Org) predicate.Org {
	return predicate.Org(sql.NotPredicates(p))
}
