// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// Proxy is the predicate function for proxy builders.
type Proxy func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Traffic is the predicate function for traffic builders.
type Traffic func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
