// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxy type in the database.
	Label = "proxy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// FieldMitmEnabled holds the string denoting the mitm_enabled field in the database.
	FieldMitmEnabled = "mitm_enabled"
	// FieldSkipHosts holds the string denoting the skip_hosts field in the database.
	FieldSkipHosts = "skip_hosts"
	// FieldIncludeHosts holds the string denoting the include_hosts field in the database.
	FieldIncludeHosts = "include_hosts"
	// FieldExcludeHosts holds the string denoting the exclude_hosts field in the database.
	FieldExcludeHosts = "exclude_hosts"
	// FieldIncludePaths holds the string denoting the include_paths field in the database.
	FieldIncludePaths = "include_paths"
	// FieldExcludePaths holds the string denoting the exclude_paths field in the database.
	FieldExcludePaths = "exclude_paths"
	// FieldUpstream holds the string denoting the upstream field in the database.
	FieldUpstream = "upstream"
	// FieldSkipBinary holds the string denoting the skip_binary field in the database.
	FieldSkipBinary = "skip_binary"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldLastStartedAt holds the string denoting the last_started_at field in the database.
	FieldLastStartedAt = "last_started_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrg holds the string denoting the org edge name in mutations.
	EdgeOrg = "org"
	// EdgeTraffic holds the string denoting the traffic edge name in mutations.
	EdgeTraffic = "traffic"
	// Table holds the table name of the proxy in the database.
	Table = "proxies"
	// OrgTable is the table that holds the org relation/edge.
	OrgTable = "proxies"
	// OrgInverseTable is the table name for the Org entity.
	// It exists in this package in order to avoid circular dependency with the "org" package.
	OrgInverseTable = "orgs"
	// OrgColumn is the table column denoting the org relation/edge.
	OrgColumn = "org_proxies"
	// TrafficTable is the table that holds the traffic relation/edge.
	TrafficTable = "traffics"
	// TrafficInverseTable is the table name for the Traffic entity.
	// It exists in this package in order to avoid circular dependency with the "traffic" package.
	TrafficInverseTable = "traffics"
	// TrafficColumn is the table column denoting the traffic relation/edge.
	TrafficColumn = "proxy_traffic"
)

// Columns holds all SQL columns for proxy fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldMode,
	FieldPort,
	FieldHost,
	FieldMitmEnabled,
	FieldSkipHosts,
	FieldIncludeHosts,
	FieldExcludeHosts,
	FieldIncludePaths,
	FieldExcludePaths,
	FieldUpstream,
	FieldSkipBinary,
	FieldActive,
	FieldLastStartedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "proxies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"org_proxies",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultPort holds the default value on creation for the "port" field.
	DefaultPort int
	// DefaultHost holds the default value on creation for the "host" field.
	DefaultHost string
	// DefaultMitmEnabled holds the default value on creation for the "mitm_enabled" field.
	DefaultMitmEnabled bool
	// DefaultSkipBinary holds the default value on creation for the "skip_binary" field.
	DefaultSkipBinary bool
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Mode defines the type for the "mode" enum field.
type Mode string

// ModeForward is the default value of the Mode enum.
const DefaultMode = ModeForward

// Mode values.
const (
	ModeForward     Mode = "forward"
	ModeReverse     Mode = "reverse"
	ModeTransparent Mode = "transparent"
)

func (m Mode) String() string {
	return string(m)
}

// ModeValidator is a validator for the "mode" field enum values. It is called by the builders before save.
func ModeValidator(m Mode) error {
	switch m {
	case ModeForward, ModeReverse, ModeTransparent:
		return nil
	default:
		return fmt.Errorf("proxy: invalid enum value for mode field: %q", m)
	}
}

// OrderOption defines the ordering options for the Proxy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByMitmEnabled orders the results by the mitm_enabled field.
func ByMitmEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMitmEnabled, opts...).ToFunc()
}

// ByUpstream orders the results by the upstream field.
func ByUpstream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstream, opts...).ToFunc()
}

// BySkipBinary orders the results by the skip_binary field.
func BySkipBinary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipBinary, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByLastStartedAt orders the results by the last_started_at field.
func ByLastStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStartedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrgField orders the results by org field.
func ByOrgField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrgStep(), sql.OrderByField(field, opts...))
	}
}

// ByTrafficCount orders the results by traffic count.
func ByTrafficCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTrafficStep(), opts...)
	}
}

// ByTraffic orders the results by traffic terms.
func ByTraffic(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTrafficStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrgStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrgInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrgTable, OrgColumn),
	)
}
func newTrafficStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TrafficInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TrafficTable, TrafficColumn),
	)
}
