// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/grokify/omniproxy/ui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldSlug, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldHost, v))
}

// MitmEnabled applies equality check predicate on the "mitm_enabled" field. It's identical to MitmEnabledEQ.
func MitmEnabled(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMitmEnabled, v))
}

// Upstream applies equality check predicate on the "upstream" field. It's identical to UpstreamEQ.
func Upstream(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpstream, v))
}

// SkipBinary applies equality check predicate on the "skip_binary" field. It's identical to SkipBinaryEQ.
func SkipBinary(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldSkipBinary, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldActive, v))
}

// LastStartedAt applies equality check predicate on the "last_started_at" field. It's identical to LastStartedAtEQ.
func LastStartedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldLastStartedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldSlug, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v Mode) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v Mode) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...Mode) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...Mode) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldMode, vs...))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPort, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldHost, v))
}

// MitmEnabledEQ applies the EQ predicate on the "mitm_enabled" field.
func MitmEnabledEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldMitmEnabled, v))
}

// MitmEnabledNEQ applies the NEQ predicate on the "mitm_enabled" field.
func MitmEnabledNEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldMitmEnabled, v))
}

// SkipHostsIsNil applies the IsNil predicate on the "skip_hosts" field.
func SkipHostsIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldSkipHosts))
}

// SkipHostsNotNil applies the NotNil predicate on the "skip_hosts" field.
func SkipHostsNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldSkipHosts))
}

// IncludeHostsIsNil applies the IsNil predicate on the "include_hosts" field.
func IncludeHostsIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldIncludeHosts))
}

// IncludeHostsNotNil applies the NotNil predicate on the "include_hosts" field.
func IncludeHostsNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldIncludeHosts))
}

// ExcludeHostsIsNil applies the IsNil predicate on the "exclude_hosts" field.
func ExcludeHostsIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExcludeHosts))
}

// ExcludeHostsNotNil applies the NotNil predicate on the "exclude_hosts" field.
func ExcludeHostsNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExcludeHosts))
}

// IncludePathsIsNil applies the IsNil predicate on the "include_paths" field.
func IncludePathsIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldIncludePaths))
}

// IncludePathsNotNil applies the NotNil predicate on the "include_paths" field.
func IncludePathsNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldIncludePaths))
}

// ExcludePathsIsNil applies the IsNil predicate on the "exclude_paths" field.
func ExcludePathsIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldExcludePaths))
}

// ExcludePathsNotNil applies the NotNil predicate on the "exclude_paths" field.
func ExcludePathsNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldExcludePaths))
}

// UpstreamEQ applies the EQ predicate on the "upstream" field.
func UpstreamEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpstream, v))
}

// UpstreamNEQ applies the NEQ predicate on the "upstream" field.
func UpstreamNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUpstream, v))
}

// UpstreamIn applies the In predicate on the "upstream" field.
func UpstreamIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUpstream, vs...))
}

// UpstreamNotIn applies the NotIn predicate on the "upstream" field.
func UpstreamNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUpstream, vs...))
}

// UpstreamGT applies the GT predicate on the "upstream" field.
func UpstreamGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUpstream, v))
}

// UpstreamGTE applies the GTE predicate on the "upstream" field.
func UpstreamGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUpstream, v))
}

// UpstreamLT applies the LT predicate on the "upstream" field.
func UpstreamLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUpstream, v))
}

// UpstreamLTE applies the LTE predicate on the "upstream" field.
func UpstreamLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUpstream, v))
}

// UpstreamContains applies the Contains predicate on the "upstream" field.
func UpstreamContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldUpstream, v))
}

// UpstreamHasPrefix applies the HasPrefix predicate on the "upstream" field.
func UpstreamHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldUpstream, v))
}

// UpstreamHasSuffix applies the HasSuffix predicate on the "upstream" field.
func UpstreamHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldUpstream, v))
}

// UpstreamIsNil applies the IsNil predicate on the "upstream" field.
func UpstreamIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldUpstream))
}

// UpstreamNotNil applies the NotNil predicate on the "upstream" field.
func UpstreamNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldUpstream))
}

// UpstreamEqualFold applies the EqualFold predicate on the "upstream" field.
func UpstreamEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldUpstream, v))
}

// UpstreamContainsFold applies the ContainsFold predicate on the "upstream" field.
func UpstreamContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldUpstream, v))
}

// SkipBinaryEQ applies the EQ predicate on the "skip_binary" field.
func SkipBinaryEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldSkipBinary, v))
}

// SkipBinaryNEQ applies the NEQ predicate on the "skip_binary" field.
func SkipBinaryNEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldSkipBinary, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldActive, v))
}

// LastStartedAtEQ applies the EQ predicate on the "last_started_at" field.
func LastStartedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldLastStartedAt, v))
}

// LastStartedAtNEQ applies the NEQ predicate on the "last_started_at" field.
func LastStartedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldLastStartedAt, v))
}

// LastStartedAtIn applies the In predicate on the "last_started_at" field.
func LastStartedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldLastStartedAt, vs...))
}

// LastStartedAtNotIn applies the NotIn predicate on the "last_started_at" field.
func LastStartedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldLastStartedAt, vs...))
}

// LastStartedAtGT applies the GT predicate on the "last_started_at" field.
func LastStartedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldLastStartedAt, v))
}

// LastStartedAtGTE applies the GTE predicate on the "last_started_at" field.
func LastStartedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldLastStartedAt, v))
}

// LastStartedAtLT applies the LT predicate on the "last_started_at" field.
func LastStartedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldLastStartedAt, v))
}

// LastStartedAtLTE applies the LTE predicate on the "last_started_at" field.
func LastStartedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldLastStartedAt, v))
}

// LastStartedAtIsNil applies the IsNil predicate on the "last_started_at" field.
func LastStartedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldLastStartedAt))
}

// LastStartedAtNotNil applies the NotNil predicate on the "last_started_at" field.
func LastStartedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldLastStartedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrg applies the HasEdge predicate on the "org" edge.
func HasOrg() predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrgTable, OrgColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrgWith applies the HasEdge predicate on the "org" edge with a given conditions (other predicates).
func HasOrgWith(preds ...predicate.Org) predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := newOrgStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTraffic applies the HasEdge predicate on the "traffic" edge.
func HasTraffic() predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TrafficTable, TrafficColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTrafficWith applies the HasEdge predicate on the "traffic" edge with a given conditions (other predicates).
func HasTrafficWith(preds ...predicate.Traffic) predicate.Proxy {
	return predicate.Proxy(func(s *sql.Selector) {
		step := newTrafficStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.NotPredicates(p))
}
