// Code generated by ent, DO NOT EDIT.

package traffic

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the traffic type in the database.
	Label = "traffic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldScheme holds the string denoting the scheme field in the database.
	FieldScheme = "scheme"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldQuery holds the string denoting the query field in the database.
	FieldQuery = "query"
	// FieldRequestHeaders holds the string denoting the request_headers field in the database.
	FieldRequestHeaders = "request_headers"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldRequestBodySize holds the string denoting the request_body_size field in the database.
	FieldRequestBodySize = "request_body_size"
	// FieldRequestIsBinary holds the string denoting the request_is_binary field in the database.
	FieldRequestIsBinary = "request_is_binary"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldStatusText holds the string denoting the status_text field in the database.
	FieldStatusText = "status_text"
	// FieldResponseHeaders holds the string denoting the response_headers field in the database.
	FieldResponseHeaders = "response_headers"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldResponseBodySize holds the string denoting the response_body_size field in the database.
	FieldResponseBodySize = "response_body_size"
	// FieldResponseIsBinary holds the string denoting the response_is_binary field in the database.
	FieldResponseIsBinary = "response_is_binary"
	// FieldResponseContentType holds the string denoting the response_content_type field in the database.
	FieldResponseContentType = "response_content_type"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldTtfbMs holds the string denoting the ttfb_ms field in the database.
	FieldTtfbMs = "ttfb_ms"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProxy holds the string denoting the proxy edge name in mutations.
	EdgeProxy = "proxy"
	// Table holds the table name of the traffic in the database.
	Table = "traffics"
	// ProxyTable is the table that holds the proxy relation/edge.
	ProxyTable = "traffics"
	// ProxyInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxyInverseTable = "proxies"
	// ProxyColumn is the table column denoting the proxy relation/edge.
	ProxyColumn = "proxy_traffic"
)

// Columns holds all SQL columns for traffic fields.
var Columns = []string{
	FieldID,
	FieldMethod,
	FieldURL,
	FieldScheme,
	FieldHost,
	FieldPath,
	FieldQuery,
	FieldRequestHeaders,
	FieldRequestBody,
	FieldRequestBodySize,
	FieldRequestIsBinary,
	FieldContentType,
	FieldStatusCode,
	FieldStatusText,
	FieldResponseHeaders,
	FieldResponseBody,
	FieldResponseBodySize,
	FieldResponseIsBinary,
	FieldResponseContentType,
	FieldStartedAt,
	FieldDurationMs,
	FieldTtfbMs,
	FieldClientIP,
	FieldError,
	FieldTags,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "traffics"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"proxy_traffic",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// HostValidator is a validator for the "host" field. It is called by the builders before save.
	HostValidator func(string) error
	// DefaultRequestBodySize holds the default value on creation for the "request_body_size" field.
	DefaultRequestBodySize int64
	// DefaultRequestIsBinary holds the default value on creation for the "request_is_binary" field.
	DefaultRequestIsBinary bool
	// DefaultResponseBodySize holds the default value on creation for the "response_body_size" field.
	DefaultResponseBodySize int64
	// DefaultResponseIsBinary holds the default value on creation for the "response_is_binary" field.
	DefaultResponseIsBinary bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Traffic queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByScheme orders the results by the scheme field.
func ByScheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheme, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByQuery orders the results by the query field.
func ByQuery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuery, opts...).ToFunc()
}

// ByRequestBodySize orders the results by the request_body_size field.
func ByRequestBodySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBodySize, opts...).ToFunc()
}

// ByRequestIsBinary orders the results by the request_is_binary field.
func ByRequestIsBinary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestIsBinary, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByStatusText orders the results by the status_text field.
func ByStatusText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusText, opts...).ToFunc()
}

// ByResponseBodySize orders the results by the response_body_size field.
func ByResponseBodySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBodySize, opts...).ToFunc()
}

// ByResponseIsBinary orders the results by the response_is_binary field.
func ByResponseIsBinary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseIsBinary, opts...).ToFunc()
}

// ByResponseContentType orders the results by the response_content_type field.
func ByResponseContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseContentType, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByTtfbMs orders the results by the ttfb_ms field.
func ByTtfbMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtfbMs, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProxyField orders the results by proxy field.
func ByProxyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyStep(), sql.OrderByField(field, opts...))
	}
}
func newProxyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProxyTable, ProxyColumn),
	)
}
