// Code generated by ent, DO NOT EDIT.

package traffic

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/grokify/omniproxy/ui/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldID, id))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldMethod, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldURL, v))
}

// Scheme applies equality check predicate on the "scheme" field. It's identical to SchemeEQ.
func Scheme(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldScheme, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldHost, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldPath, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldQuery, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodySize applies equality check predicate on the "request_body_size" field. It's identical to RequestBodySizeEQ.
func RequestBodySize(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldRequestBodySize, v))
}

// RequestIsBinary applies equality check predicate on the "request_is_binary" field. It's identical to RequestIsBinaryEQ.
func RequestIsBinary(v bool) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldRequestIsBinary, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldContentType, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldStatusCode, v))
}

// StatusText applies equality check predicate on the "status_text" field. It's identical to StatusTextEQ.
func StatusText(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldStatusText, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodySize applies equality check predicate on the "response_body_size" field. It's identical to ResponseBodySizeEQ.
func ResponseBodySize(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseBodySize, v))
}

// ResponseIsBinary applies equality check predicate on the "response_is_binary" field. It's identical to ResponseIsBinaryEQ.
func ResponseIsBinary(v bool) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseIsBinary, v))
}

// ResponseContentType applies equality check predicate on the "response_content_type" field. It's identical to ResponseContentTypeEQ.
func ResponseContentType(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseContentType, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldStartedAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldDurationMs, v))
}

// TtfbMs applies equality check predicate on the "ttfb_ms" field. It's identical to TtfbMsEQ.
func TtfbMs(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldTtfbMs, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldClientIP, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldCreatedAt, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldMethod, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldURL, v))
}

// SchemeEQ applies the EQ predicate on the "scheme" field.
func SchemeEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldScheme, v))
}

// SchemeNEQ applies the NEQ predicate on the "scheme" field.
func SchemeNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldScheme, v))
}

// SchemeIn applies the In predicate on the "scheme" field.
func SchemeIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldScheme, vs...))
}

// SchemeNotIn applies the NotIn predicate on the "scheme" field.
func SchemeNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldScheme, vs...))
}

// SchemeGT applies the GT predicate on the "scheme" field.
func SchemeGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldScheme, v))
}

// SchemeGTE applies the GTE predicate on the "scheme" field.
func SchemeGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldScheme, v))
}

// SchemeLT applies the LT predicate on the "scheme" field.
func SchemeLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldScheme, v))
}

// SchemeLTE applies the LTE predicate on the "scheme" field.
func SchemeLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldScheme, v))
}

// SchemeContains applies the Contains predicate on the "scheme" field.
func SchemeContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldScheme, v))
}

// SchemeHasPrefix applies the HasPrefix predicate on the "scheme" field.
func SchemeHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldScheme, v))
}

// SchemeHasSuffix applies the HasSuffix predicate on the "scheme" field.
func SchemeHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldScheme, v))
}

// SchemeEqualFold applies the EqualFold predicate on the "scheme" field.
func SchemeEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldScheme, v))
}

// SchemeContainsFold applies the ContainsFold predicate on the "scheme" field.
func SchemeContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldScheme, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldHost, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldPath, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryIsNil applies the IsNil predicate on the "query" field.
func QueryIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldQuery))
}

// QueryNotNil applies the NotNil predicate on the "query" field.
func QueryNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldQuery))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldQuery, v))
}

// RequestHeadersIsNil applies the IsNil predicate on the "request_headers" field.
func RequestHeadersIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldRequestHeaders))
}

// RequestHeadersNotNil applies the NotNil predicate on the "request_headers" field.
func RequestHeadersNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldRequestHeaders))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...[]byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...[]byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldRequestBody))
}

// RequestBodySizeEQ applies the EQ predicate on the "request_body_size" field.
func RequestBodySizeEQ(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldRequestBodySize, v))
}

// RequestBodySizeNEQ applies the NEQ predicate on the "request_body_size" field.
func RequestBodySizeNEQ(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldRequestBodySize, v))
}

// RequestBodySizeIn applies the In predicate on the "request_body_size" field.
func RequestBodySizeIn(vs ...int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldRequestBodySize, vs...))
}

// RequestBodySizeNotIn applies the NotIn predicate on the "request_body_size" field.
func RequestBodySizeNotIn(vs ...int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldRequestBodySize, vs...))
}

// RequestBodySizeGT applies the GT predicate on the "request_body_size" field.
func RequestBodySizeGT(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldRequestBodySize, v))
}

// RequestBodySizeGTE applies the GTE predicate on the "request_body_size" field.
func RequestBodySizeGTE(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldRequestBodySize, v))
}

// RequestBodySizeLT applies the LT predicate on the "request_body_size" field.
func RequestBodySizeLT(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldRequestBodySize, v))
}

// RequestBodySizeLTE applies the LTE predicate on the "request_body_size" field.
func RequestBodySizeLTE(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldRequestBodySize, v))
}

// RequestIsBinaryEQ applies the EQ predicate on the "request_is_binary" field.
func RequestIsBinaryEQ(v bool) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldRequestIsBinary, v))
}

// RequestIsBinaryNEQ applies the NEQ predicate on the "request_is_binary" field.
func RequestIsBinaryNEQ(v bool) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldRequestIsBinary, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeIsNil applies the IsNil predicate on the "content_type" field.
func ContentTypeIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldContentType))
}

// ContentTypeNotNil applies the NotNil predicate on the "content_type" field.
func ContentTypeNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldContentType))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldContentType, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldStatusCode, v))
}

// StatusTextEQ applies the EQ predicate on the "status_text" field.
func StatusTextEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldStatusText, v))
}

// StatusTextNEQ applies the NEQ predicate on the "status_text" field.
func StatusTextNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldStatusText, v))
}

// StatusTextIn applies the In predicate on the "status_text" field.
func StatusTextIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldStatusText, vs...))
}

// StatusTextNotIn applies the NotIn predicate on the "status_text" field.
func StatusTextNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldStatusText, vs...))
}

// StatusTextGT applies the GT predicate on the "status_text" field.
func StatusTextGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldStatusText, v))
}

// StatusTextGTE applies the GTE predicate on the "status_text" field.
func StatusTextGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldStatusText, v))
}

// StatusTextLT applies the LT predicate on the "status_text" field.
func StatusTextLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldStatusText, v))
}

// StatusTextLTE applies the LTE predicate on the "status_text" field.
func StatusTextLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldStatusText, v))
}

// StatusTextContains applies the Contains predicate on the "status_text" field.
func StatusTextContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldStatusText, v))
}

// StatusTextHasPrefix applies the HasPrefix predicate on the "status_text" field.
func StatusTextHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldStatusText, v))
}

// StatusTextHasSuffix applies the HasSuffix predicate on the "status_text" field.
func StatusTextHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldStatusText, v))
}

// StatusTextIsNil applies the IsNil predicate on the "status_text" field.
func StatusTextIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldStatusText))
}

// StatusTextNotNil applies the NotNil predicate on the "status_text" field.
func StatusTextNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldStatusText))
}

// StatusTextEqualFold applies the EqualFold predicate on the "status_text" field.
func StatusTextEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldStatusText, v))
}

// StatusTextContainsFold applies the ContainsFold predicate on the "status_text" field.
func StatusTextContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldStatusText, v))
}

// ResponseHeadersIsNil applies the IsNil predicate on the "response_headers" field.
func ResponseHeadersIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldResponseHeaders))
}

// ResponseHeadersNotNil applies the NotNil predicate on the "response_headers" field.
func ResponseHeadersNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldResponseHeaders))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...[]byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...[]byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v []byte) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodySizeEQ applies the EQ predicate on the "response_body_size" field.
func ResponseBodySizeEQ(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseBodySize, v))
}

// ResponseBodySizeNEQ applies the NEQ predicate on the "response_body_size" field.
func ResponseBodySizeNEQ(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldResponseBodySize, v))
}

// ResponseBodySizeIn applies the In predicate on the "response_body_size" field.
func ResponseBodySizeIn(vs ...int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldResponseBodySize, vs...))
}

// ResponseBodySizeNotIn applies the NotIn predicate on the "response_body_size" field.
func ResponseBodySizeNotIn(vs ...int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldResponseBodySize, vs...))
}

// ResponseBodySizeGT applies the GT predicate on the "response_body_size" field.
func ResponseBodySizeGT(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldResponseBodySize, v))
}

// ResponseBodySizeGTE applies the GTE predicate on the "response_body_size" field.
func ResponseBodySizeGTE(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldResponseBodySize, v))
}

// ResponseBodySizeLT applies the LT predicate on the "response_body_size" field.
func ResponseBodySizeLT(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldResponseBodySize, v))
}

// ResponseBodySizeLTE applies the LTE predicate on the "response_body_size" field.
func ResponseBodySizeLTE(v int64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldResponseBodySize, v))
}

// ResponseIsBinaryEQ applies the EQ predicate on the "response_is_binary" field.
func ResponseIsBinaryEQ(v bool) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseIsBinary, v))
}

// ResponseIsBinaryNEQ applies the NEQ predicate on the "response_is_binary" field.
func ResponseIsBinaryNEQ(v bool) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldResponseIsBinary, v))
}

// ResponseContentTypeEQ applies the EQ predicate on the "response_content_type" field.
func ResponseContentTypeEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldResponseContentType, v))
}

// ResponseContentTypeNEQ applies the NEQ predicate on the "response_content_type" field.
func ResponseContentTypeNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldResponseContentType, v))
}

// ResponseContentTypeIn applies the In predicate on the "response_content_type" field.
func ResponseContentTypeIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldResponseContentType, vs...))
}

// ResponseContentTypeNotIn applies the NotIn predicate on the "response_content_type" field.
func ResponseContentTypeNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldResponseContentType, vs...))
}

// ResponseContentTypeGT applies the GT predicate on the "response_content_type" field.
func ResponseContentTypeGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldResponseContentType, v))
}

// ResponseContentTypeGTE applies the GTE predicate on the "response_content_type" field.
func ResponseContentTypeGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldResponseContentType, v))
}

// ResponseContentTypeLT applies the LT predicate on the "response_content_type" field.
func ResponseContentTypeLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldResponseContentType, v))
}

// ResponseContentTypeLTE applies the LTE predicate on the "response_content_type" field.
func ResponseContentTypeLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldResponseContentType, v))
}

// ResponseContentTypeContains applies the Contains predicate on the "response_content_type" field.
func ResponseContentTypeContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldResponseContentType, v))
}

// ResponseContentTypeHasPrefix applies the HasPrefix predicate on the "response_content_type" field.
func ResponseContentTypeHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldResponseContentType, v))
}

// ResponseContentTypeHasSuffix applies the HasSuffix predicate on the "response_content_type" field.
func ResponseContentTypeHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldResponseContentType, v))
}

// ResponseContentTypeIsNil applies the IsNil predicate on the "response_content_type" field.
func ResponseContentTypeIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldResponseContentType))
}

// ResponseContentTypeNotNil applies the NotNil predicate on the "response_content_type" field.
func ResponseContentTypeNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldResponseContentType))
}

// ResponseContentTypeEqualFold applies the EqualFold predicate on the "response_content_type" field.
func ResponseContentTypeEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldResponseContentType, v))
}

// ResponseContentTypeContainsFold applies the ContainsFold predicate on the "response_content_type" field.
func ResponseContentTypeContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldResponseContentType, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldStartedAt, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldDurationMs, v))
}

// TtfbMsEQ applies the EQ predicate on the "ttfb_ms" field.
func TtfbMsEQ(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldTtfbMs, v))
}

// TtfbMsNEQ applies the NEQ predicate on the "ttfb_ms" field.
func TtfbMsNEQ(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldTtfbMs, v))
}

// TtfbMsIn applies the In predicate on the "ttfb_ms" field.
func TtfbMsIn(vs ...float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldTtfbMs, vs...))
}

// TtfbMsNotIn applies the NotIn predicate on the "ttfb_ms" field.
func TtfbMsNotIn(vs ...float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldTtfbMs, vs...))
}

// TtfbMsGT applies the GT predicate on the "ttfb_ms" field.
func TtfbMsGT(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldTtfbMs, v))
}

// TtfbMsGTE applies the GTE predicate on the "ttfb_ms" field.
func TtfbMsGTE(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldTtfbMs, v))
}

// TtfbMsLT applies the LT predicate on the "ttfb_ms" field.
func TtfbMsLT(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldTtfbMs, v))
}

// TtfbMsLTE applies the LTE predicate on the "ttfb_ms" field.
func TtfbMsLTE(v float64) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldTtfbMs, v))
}

// TtfbMsIsNil applies the IsNil predicate on the "ttfb_ms" field.
func TtfbMsIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldTtfbMs))
}

// TtfbMsNotNil applies the NotNil predicate on the "ttfb_ms" field.
func TtfbMsNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldTtfbMs))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPIsNil applies the IsNil predicate on the "client_ip" field.
func ClientIPIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldClientIP))
}

// ClientIPNotNil applies the NotNil predicate on the "client_ip" field.
func ClientIPNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldClientIP))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldClientIP, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Traffic {
	return predicate.Traffic(sql.FieldContainsFold(FieldError, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Traffic {
	return predicate.Traffic(sql.FieldNotNull(FieldTags))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Traffic {
	return predicate.Traffic(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.Traffic {
	return predicate.Traffic(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.Traffic {
	return predicate.Traffic(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Traffic) predicate.Traffic {
	return predicate.Traffic(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Traffic) predicate.Traffic {
	return predicate.Traffic(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Traffic) predicate.Traffic {
	return predicate.Traffic(sql.NotPredicates(p))
}
